### ISSUE TITLE
[pyclustering.nnet.sync] Multi-core implementation

### ISSUE THREAD

**Issue by annoviko** [annoviko/pyclustering#170]
Multi-core implementation should be introduced. Prototype has been successfully tested on 24-core machine and shows advantages.

**Comment by TemetNosce95** [comment]
Hello, I'm testing your implementation of X-means clustering algorithm in my research work, and the performance with some datasets that contains 4 or 5 million points is not exactly what i've expected. The future multicore version of this package will improve the performance of all the algorithms in the package (including X-means) or only some of them?

**Comment by annoviko** [comment]
@TemetNosce95, I have started multi-core implementation for X-Means. And fixed clustering result before optimization to be able to compare results. I have found that in case of millions points situation is not so dramatic, there are some results of performance test (before optimization):
```
Random sample: (size:600000) ', Execution time: ' 6.189236562524233
Random sample: (size:1200000) ', Execution time: ' 12.69288331531482
Random sample: (size:1800000) ', Execution time: ' 18.732027960623853
```

Are you sure that you have used 'ccore' flag to increase performance (pass clustering process to C/C++ implementation of the pyclustering library, so called CCORE)?
```python
xmeans_instance = xmeans(data_points, start_centers, 20, ccore = True);
```

And may I ask to provide data (for example upload to somewhere) for testing?
Could you please provide answer in https://github.com/annoviko/pyclustering/issues/372 ?

**Comment by annoviko** [comment]
```
[ RUN      ] utest_sync.perf_test_2500_sequential
[       OK ] utest_sync.perf_test_2500_sequential (83 ms)
[ RUN      ] utest_sync.perf_test_2500_parallel
[       OK ] utest_sync.perf_test_2500_parallel (81 ms)
[ RUN      ] utest_sync.perf_test_3600_sequential
[       OK ] utest_sync.perf_test_3600_sequential (81 ms)
[ RUN      ] utest_sync.perf_test_3600_parallel
[       OK ] utest_sync.perf_test_3600_parallel (77 ms)
```

**Comment by lemonysoft** [comment]
What should I do for using multi core of CURE? Thanks.

![image](https://user-images.githubusercontent.com/30117203/196204711-995fbe17-e0e6-4381-8d61-061fd65ef3ae.png)
