### ISSUE TITLE
Adding support for (1) rectangular images and (2) user-defined linking and feeding weight matrices

### ISSUE THREAD

**Issue by madratman** [annoviko/pyclustering#259]
(Maybe this should be broken into two issues)

- To use `GRID_FOUR` or `GRID_EIGHT` type connectivity, one needs to restrict to a perfect square number of (pcnn at least) oscillators. 
This restrics the scope of the library(at least pcnn, which I am using) to (cropped) square images.  
Here's the relevant code block from [network.cpp](https://github.com/annoviko/pyclustering/blob/master/ccore/ccore/network.cpp#L200-L204):
```
void network::create_grid_four_connections() {
	const double conv_side_size = std::sqrt((double) num_osc);
	if (conv_side_size - std::floor(conv_side_size) > 0) {
		throw std::runtime_error("Invalid number of oscillators in the network for the grid structure");
	}
```
And of course, making type `GRID_EIGHT` calls the previous method only. [code block](https://github.com/annoviko/pyclustering/blob/master/ccore/ccore/network.cpp#L236)  
```
https://github.com/annoviko/pyclustering/blob/master/ccore/ccore/network.cpp#L236
```

- The feeding and linking weight "matrix" in pcnn (haven't checked out other networks) is defined just as a single integer. Hence one can only have an array of equal weights.
This should be improved to allow users to define custom linkages like gaussian, or inverse of distance. 
[code block 1](https://github.com/annoviko/pyclustering/blob/master/ccore/ccore/pcnn.h#L34 -L35)
```
typedef struct pcnn_parameters {
...
	double W = 1.0;
	double M = 1.0;
```

[code block 2](https://github.com/annoviko/pyclustering/blob/master/ccore/ccore/pcnn.cpp#L36-L41)

```

		for (std::vector<unsigned int>::const_iterator iter = neighbors.begin(); iter != neighbors.end(); iter++) {
			const double output_neighbor = m_oscillators[(*iter)].output;

			feeding_influence += output_neighbor * m_params.M;
			linking_influence += output_neighbor * m_params.W;
		}
```

**Comment by annoviko** [comment]
I think the first part of the issue has been resolved:
https://github.com/annoviko/pyclustering/commit/eab634c95a31a04b282f0cb3204eecd4463b493c

Thank you for your pull request. It has been merged with some changes: added the same support to other oscillatory networks, added unit-tests.

**Comment by annoviko** [comment]
Anyway such feature (the first part) should be also added to the pyclustering (python) implementation. I will take care about it.

**Comment by annoviko** [comment]
Support of rectangular structures and images by base class network and PCNN is implemented: https://github.com/annoviko/pyclustering/commit/d9dde0720f87ae10c33ad2545e3f9d95ab409c63 .

**Comment by annoviko** [comment]
Support of weight matrices is added. Adjacency class collection can be used for that purpose:
- adjacency_weight_list
- adjacency_matrix

Both implement adajcency interface.
