### ISSUE TITLE
Python CURE always finds max two representative points

### ISSUE THREAD

**Issue by aivanni** [annoviko/pyclustering#310]
Possible solution in cure.py line 374:

`

            for point in merged_cluster.points:

                minimal_distance = 0;

                if (index == 0):

                    minimal_distance = euclidean_distance(point, merged_cluster.mean);

                    #minimal_distance = euclidean_distance_sqrt(point, merged_cluster.mean);

                else:

                    minimal_distance = min([euclidean_distance(point, p) for p in temporary])

`

The example with 3 clusters won't work -> need to decrease compression rate.

Also typo in line 201:

`

             item.ditance = distance;

`

**Comment by annoviko** [comment]
@aivanni, thank you for the bug report and for the bug correction! The proposed changes have been implemented for Python implementation and for C/C++ implementation (core of the pyclustering) for both branches at following revisions:
**master**: https://github.com/annoviko/pyclustering/commit/a904849f7705689cea4d856ae5d978c64646a34e
**0.6.x**: https://github.com/annoviko/pyclustering/commit/cf3547da54d45c222a78baf6e1d4267f368abfa0
