### ISSUE TITLE
ccore.dll is not run by python

### ISSUE THREAD

**Issue by aivanni** [annoviko/pyclustering#312]
Hello, 

when running clustering with flag ccore=True. I get the following error:

`

    Traceback (most recent call last):
      File "cure_test.py", line 15, in <module>
        cure_instance.process();
      File "c:\Python34\lib\site-packages\pyclustering\cluster\cure.py", line 138, in process
        cure_data_pointer = wrapper.cure_algorithm(self.__pointer_data, self.__number_cluster,   self.__number_represent_points, self.__compression);
      File "c:\Python34\lib\site-packages\pyclustering\core\cure_wrapper.py", line 34, in cure_algorithm
        ccore = cdll.LoadLibrary(PATH_DLL_CCORE_64);
      File "c:\Python34\lib\ctypes\__init__.py", line 429, in LoadLibrary
        return self._dlltype(name)
      File "c:\Python34\lib\ctypes\__init__.py", line 351, in init
        self._handle = _dlopen(self._name, mode)
    OSError: [WinError 193] %1 is not a valid Win32 application

`

I am using the following version of python:

Python 3.4.3 (v3.4.3:9b73f1c3e601, Feb 24 2015, 22:44:40) [MSC v.1600 64 bit (AMD64)] on win32

Can it be a compiler incompatibility? What compiler do you use do build ccore.dll? Thank you!

**Comment by annoviko** [comment]
@aivanni, the problem is that ccore.dll is compiled for 64-bit operating system (by default), but you are runnung it on 32-bit operating system. If you need to use it on 32-bit operating system than following actions should be performed:
1. Build CCORE library for 32-bit operating system.
2. Use Python 32-bit version.

I have used Microsoft Visual Studio 2015 for compilation. So you can re-built it using 'ccore.sln' that is located in 'pyclustering/ccore/ccore.sln', but still you need to download 32-bit version of Python.

Could you please try it?

**Comment by aivanni** [comment]
@annoviko I forgot to mention that system is in fact 64-bit Windows 10. Will try to compile it anyway.

**Comment by annoviko** [comment]
@aivanni, so you are using 64-bit version of Python on 64-bit version of operation system? I have checked the issue for Windows 7 (64-bit) and it works without 'ccore.dll' rebuilding (by default it is compiled for 64-bit version). But anyway I will check again what can be wrong and ask @Polladin to check the issue also.

**Comment by annoviko** [comment]
@Polladin, could you please clone current version of the master branch and run some algorithms from the library that uses 'ccore.dll' on 64-bit version (ccore flag is on).

**Comment by aivanni** [comment]
@annoviko, right I am using python 64-bit and OS 64-bit. The problem is now eventually solved by installing Microsoft Visual Studio 2015. So probably older versions of some C/C++ standard libraries were incompatible or maybe these libraries were 32-bit themselves. Thank you for looking into it!

**Comment by annoviko** [comment]
@aivanni, thank you for your answer, I think this requirement (C++ libraries of Microsoft Visual Studio 2015) should be reflected in ReadMe and project description.
