### ISSUE TITLE
Examples and Benchmarks

### ISSUE THREAD

**Issue by JoshuaC3** [annoviko/pyclustering#319]
An interesting package. It would be _very_ interesting if there was a set of examples. A set of benchmarks so that one could quickly compare algorithms within the package itself would be great. Further, benchmarks against other clustering algorithms would be helpful.

**Comment by annoviko** [comment]
Hello, @JoshuaC3 , thank you! Each clustering algorithm as well as oscillatory/neural network model has set of examples. You can easily find them:
For cluster analysis:
```bash
andrei@linuxmachine:~/workspace/pyclustering$ ls pyclustering/cluster/examples/ -1
agglomerative_examples.py
birch_examples.py
clarans_examples.py
cure_examples.py
cure_william_example.py
dbscan_examples.py
dbscan_segmentation.py
general_examples.py
hsyncnet_examples.py
__init__.py
kmeans_examples.py
kmeans_segmentation.py
kmedians_examples.py
kmedoids_examples.py
optics_examples.py
rock_examples.py
syncnet_examples.py
syncsom_examples.py
syncsom_segmentation.py
xmeans_examples.py
```

Each module has example that demonstrates how it is working. For demonstration FCPS dataset is used. You just need to run examples of an algorithm that is interesting for you.

To make it convinient, you can clone the code and launch it eclipse:
![pyclustering examples](https://cloud.githubusercontent.com/assets/6785869/22606492/1dcf8aaa-ea65-11e6-895a-c6a52ab3bfe1.png)

![screenshot from 2017-02-03 23 06 18](https://cloud.githubusercontent.com/assets/6785869/22606603/7baabb0e-ea65-11e6-842d-ba733922814c.png)

**Comment by JoshuaC3** [comment]
Thank you. I see them now. It was a little tricky to find. Everyone seems to have different ideas about where to put them. Some put them in the main folder, some in a subfolder like docs and so on.

**Comment by annoviko** [comment]
@JushuaC3, I guess you are right and it's much better to place them in root of the project - it would much easier to find them in this way.

**Comment by annoviko** [comment]
Have provide much more information in README files - links, examples.
