### ISSUE TITLE
Median calculation for even number of points looks incorrect

### ISSUE THREAD

**Issue by nwhitaker** [annoviko/pyclustering#320]
This code looks incorrect to me:
if ( (length_cluster % 2) and (relative_index_median + 1 < len(sorted_cluster)) ):

length_cluster % 2 will be zero exactly when there is an even number of points. So if there is an even number of points, the if condition will be false.

I believe this line should be:
if (length_cluster % 2 == 0):

The second part of the clause should be unnecessary, because we already know the cluster is not empty and the cluster has an even number of points.

**Comment by annoviko** [comment]
Hello, @nwhitaker 
Thank you for the issue, I agree with your arguments and I have introduced provided changes to the code.

**Comment by nwhitaker** [comment]
Thank you!
