### ISSUE TITLE
[pyclustering.cluster.xmeans] MNDL score

### ISSUE THREAD

**Issue by Nibbles4** [annoviko/pyclustering#328]
Hi,
I'm currently implementing X-means with MNDL criterion myself and had a look at your implementation for MNDL scores and noticed 2 things:
- You use addition instead of multiplication in your term for Ks:
 https://github.com/annoviko/pyclustering/blob/master/pyclustering/cluster/xmeans.py#L330
 According to [1] (11) it should be `Ks = ( 2.0 * alpha * sigma / (N ** 0.5) ) * ( (alpha ** 2.0) * sigma_sqrt / N + W - Kw / 2.0 ) ** 0.5;`
- This for-loop seems to effectively multiply the final MNDL score by the number of clusters:
 https://github.com/annoviko/pyclustering/blob/master/pyclustering/cluster/xmeans.py#L328-L343

[1] Mahdi Shahbaba and Soosan Beheshti. "Improving X-means clustering with MNDL." 2012 11th International Conference on Information Science, Signal Processing and their Applications (ISSPA).

**Comment by annoviko** [comment]
Hello, @Nibbles4 ,

Thank you for the bug reporting! And thank you for your comment about the for-loop. I will correct the problem and optimize the code.

**Comment by annoviko** [comment]
Have done at the revision https://github.com/annoviko/pyclustering/commit/7c264beae02d10e3ca337db95efc3a3a195b3e1b .
