### ISSUE TITLE
Installing under Docker

### ISSUE THREAD

**Issue by pconway11** [annoviko/pyclustering#348]
I'm trying to install in a docker container with ubuntu...

For some reason it keeps install ccore.dll in a win directory and not ccore.so in linux

Step 9/14 : RUN python3 platform1.py
 ---> Running in 41fe8fdb1a58
[CCORE BUILD] Current platform: linux
[CCORE BUILD] CCORE library should be built for linux
 ---> ee3ec14fcaca
Removing intermediate container 41fe8fdb1a58
Step 10/14 : RUN find / -name ccore.dll
 ---> Running in 188b8aca20dc
/usr/local/lib/python3.5/dist-packages/pyclustering/core/x64/win/ccore.dll
 ---> e556ffd246ff
Removing intermediate container 188b8aca20dc
Step 11/14 : RUN ls /usr/local/lib/python3.5/dist-packages/pyclustering/core/x64/win/
 ---> Running in 672a107e3479
ccore.dll
 ---> 4353eeac4e1c
Removing intermediate container 672a107e3479
Step 12/14 : RUN ls /usr/local/lib/python3.5/dist-packages/pyclustering/core/x64/linux/
 ---> Running in 9039fe117393
ls: cannot access '/usr/local/lib/python3.5/dist-packages/pyclustering/core/x64/linux/': No such file or directory

**Comment by annoviko** [comment]
Hello, @pconway11,

ccode.dll is included by default that why it is located in ... .../pyclustering/core/x64/win/ccore.dll.

As I can see system has identified that linux version of 'ccore' should be built:
```bash
[CCORE BUILD] Current platform: linux
[CCORE BUILD] CCORE library should be built for linux
```

Could you please provide log of compilation of 'ccore' library? Log looks like this:
```bash
Installing collected packages: pyclustering
  Running setup.py install for pyclustering
    [CCORE BUILD] Current platform: linux
    [CCORE BUILD] CCORE library should be built for linux
    Build CCORE library...
    /tmp/pip_build_root/pyclustering
    rm -rf ../pyclustering/core/x64/linux
    mkdir ../pyclustering/core/x64/linux
    make -f ccore.mk
    make[1]: Entering directory `/tmp/pip_build_root/pyclustering/ccore'
    g++ -O3 -MMD -MP -std=c++1y -fPIC -c  -Isrc/ src/ccore.cpp -o src/ccore.o
    g++ -O3 -MMD -MP -std=c++1y -fPIC -c  -Isrc/ src/interface/agglomerative_interface.cpp -o src/interface/agglomerative_interface.o
... ... ...
```

Probably compilation of the core library has failed and therefore there is no 'ccore.so'. Make sure that your compiler supports C++14.

**Comment by pconway11** [comment]
I cant see the output of the pip install ...but I tried a workaround to download the and build manually.
The build works...but when I call xmeans I get Segmentation Fault
(I ran pip3 install and copied the so file to the correct directory)

Step 10/16 : RUN make ccore
 ---> Running in f191891f5925
rm -rf ../pyclustering/core/x64/linux
mkdir ../pyclustering/core/x64/linux
make -f ccore.mk
make[1]: Entering directory '/opt/pyclustering-0.6.6/ccore'
g++ -O3 -MMD -MP -std=c++1y -fPIC -c  -Isrc/ src/ccore.cpp -o src/ccore.o
g++ -O3 -MMD -MP -std=c++1y -fPIC -c  -Isrc/ src/interface/agglomerative_interface.cpp -o src/interface/agglomerative_interface.o
g++ -O3 -MMD -MP -std=c++1y -fPIC -c  -Isrc/ src/interface/dbscan_interface.cpp -o src/interface/dbscan_interface.o
g++ -O3 -MMD -MP -std=c++1y -fPIC -c  -Isrc/ src/interface/cure_interface.cpp -o src/interface/cure_interface.o
g++ -O3 -MMD -MP -std=c++1y -fPIC -c  -Isrc/ src/interface/kmeans_interface.cpp -o src/interface/kmeans_interface.o
g++ -O3 -MMD -MP -std=c++1y -fPIC -c  -Isrc/ src/interface/kmedians_interface.cpp -o src/interface/kmedians_interface.o
g++ -O3 -MMD -MP -std=c++1y -fPIC -c  -Isrc/ src/interface/kmedoids_interface.cpp -o src/interface/kmedoids_interface.o
g++ -O3 -MMD -MP -std=c++1y -fPIC -c  -Isrc/ src/interface/pcnn_interface.cpp -o src/interface/pcnn_interface.o
g++ -O3 -MMD -MP -std=c++1y -fPIC -c  -Isrc/ src/interface/pyclustering_package.cpp -o src/interface/pyclustering_package.o
g++ -O3 -MMD -MP -std=c++1y -fPIC -c  -Isrc/ src/interface/rock_interface.cpp -o src/interface/rock_interface.o
g++ -O3 -MMD -MP -std=c++1y -fPIC -c  -Isrc/ src/container/adjacency_bit_matrix.cpp -o src/container/adjacency_bit_matrix.o
g++ -O3 -MMD -MP -std=c++1y -fPIC -c  -Isrc/ src/container/adjacency_connector.cpp -o src/container/adjacency_connector.o
g++ -O3 -MMD -MP -std=c++1y -fPIC -c  -Isrc/ src/container/adjacency_list.cpp -o src/container/adjacency_list.o
g++ -O3 -MMD -MP -std=c++1y -fPIC -c  -Isrc/ src/container/adjacency_matrix.cpp -o src/container/adjacency_matrix.o
g++ -O3 -MMD -MP -std=c++1y -fPIC -c  -Isrc/ src/container/adjacency_weight_list.cpp -o src/container/adjacency_weight_list.o
g++ -O3 -MMD -MP -std=c++1y -fPIC -c  -Isrc/ src/container/kdtree.cpp -o src/container/kdtree.o
g++ -O3 -MMD -MP -std=c++1y -fPIC -c  -Isrc/ src/cluster/agglomerative.cpp -o src/cluster/agglomerative.o
g++ -O3 -MMD -MP -std=c++1y -fPIC -c  -Isrc/ src/cluster/cluster_algorithm.cpp -o src/cluster/cluster_algorithm.o
g++ -O3 -MMD -MP -std=c++1y -fPIC -c  -Isrc/ src/cluster/cluster_data.cpp -o src/cluster/cluster_data.o
g++ -O3 -MMD -MP -std=c++1y -fPIC -c  -Isrc/ src/cluster/cure.cpp -o src/cluster/cure.o
g++ -O3 -MMD -MP -std=c++1y -fPIC -c  -Isrc/ src/cluster/cure_data.cpp -o src/cluster/cure_data.o
g++ -O3 -MMD -MP -std=c++1y -fPIC -c  -Isrc/ src/cluster/dbscan.cpp -o src/cluster/dbscan.o
g++ -O3 -MMD -MP -std=c++1y -fPIC -c  -Isrc/ src/cluster/dbscan_data.cpp -o src/cluster/dbscan_data.o
g++ -O3 -MMD -MP -std=c++1y -fPIC -c  -Isrc/ src/cluster/hsyncnet.cpp -o src/cluster/hsyncnet.o
g++ -O3 -MMD -MP -std=c++1y -fPIC -c  -Isrc/ src/cluster/kmeans_data.cpp -o src/cluster/kmeans_data.o
g++ -O3 -MMD -MP -std=c++1y -fPIC -c  -Isrc/ src/cluster/kmeans.cpp -o src/cluster/kmeans.o
g++ -O3 -MMD -MP -std=c++1y -fPIC -c  -Isrc/ src/cluster/kmedians.cpp -o src/cluster/kmedians.o
g++ -O3 -MMD -MP -std=c++1y -fPIC -c  -Isrc/ src/cluster/kmedians_data.cpp -o src/cluster/kmedians_data.o
g++ -O3 -MMD -MP -std=c++1y -fPIC -c  -Isrc/ src/cluster/kmedoids.cpp -o src/cluster/kmedoids.o
g++ -O3 -MMD -MP -std=c++1y -fPIC -c  -Isrc/ src/cluster/kmedoids_data.cpp -o src/cluster/kmedoids_data.o
g++ -O3 -MMD -MP -std=c++1y -fPIC -c  -Isrc/ src/cluster/rock.cpp -o src/cluster/rock.o
g++ -O3 -MMD -MP -std=c++1y -fPIC -c  -Isrc/ src/cluster/syncnet.cpp -o src/cluster/syncnet.o
g++ -O3 -MMD -MP -std=c++1y -fPIC -c  -Isrc/ src/cluster/xmeans.cpp -o src/cluster/xmeans.o
g++ -O3 -MMD -MP -std=c++1y -fPIC -c  -Isrc/ src/differential/differ_factor.cpp -o src/differential/differ_factor.o
g++ -O3 -MMD -MP -std=c++1y -fPIC -c  -Isrc/ src/nnet/legion.cpp -o src/nnet/legion.o
g++ -O3 -MMD -MP -std=c++1y -fPIC -c  -Isrc/ src/nnet/pcnn.cpp -o src/nnet/pcnn.o
g++ -O3 -MMD -MP -std=c++1y -fPIC -c  -Isrc/ src/nnet/som.cpp -o src/nnet/som.o
g++ -O3 -MMD -MP -std=c++1y -fPIC -c  -Isrc/ src/nnet/sync.cpp -o src/nnet/sync.o
g++ -O3 -MMD -MP -std=c++1y -fPIC -c  -Isrc/ src/nnet/syncpr.cpp -o src/nnet/syncpr.o
g++ -O3 -MMD -MP -std=c++1y -fPIC -c  -Isrc/ src/utils.cpp -o src/utils.o
g++ -O3 -MMD -MP -std=c++1y -fPIC -c  -Isrc/ src/tsp/ant_colony.cpp -o src/tsp/ant_colony.o
g++ -O3 -MMD -MP -std=c++1y -fPIC -c  -Isrc/ src/tsp/distance_matrix.cpp -o src/tsp/distance_matrix.o
g++ -O3 -MMD -MP -std=c++1y -fPIC -c  -Isrc/ src/cluster/ant_clustering_mean.cpp -o src/cluster/ant_clustering_mean.o
g++ -O3 -static-libstdc++ -shared src/ccore.o src/interface/agglomerative_interface.o src/interface/dbscan_interface.o src/interface/cure_interface.o src/interface/kmeans_interface.o src/interface/kmedians_interface.o src/interface/kmedoids_interface.o src/interface/pcnn_interface.o src/interface/pyclustering_package.o src/interface/rock_interface.o src/container/adjacency_bit_matrix.o src/container/adjacency_connector.o src/container/adjacency_list.o src/container/adjacency_matrix.o src/container/adjacency_weight_list.o src/container/kdtree.o src/cluster/agglomerative.o src/cluster/cluster_algorithm.o src/cluster/cluster_data.o src/cluster/cure.o src/cluster/cure_data.o src/cluster/dbscan.o src/cluster/dbscan_data.o src/cluster/hsyncnet.o src/cluster/kmeans_data.o src/cluster/kmeans.o src/cluster/kmedians.o src/cluster/kmedians_data.o src/cluster/kmedoids.o src/cluster/kmedoids_data.o src/cluster/rock.o src/cluster/syncnet.o src/cluster/xmeans.o src/differential/differ_factor.o src/nnet/legion.o src/nnet/pcnn.o src/nnet/som.o src/nnet/sync.o src/nnet/syncpr.o src/utils.o src/tsp/ant_colony.o src/tsp/distance_matrix.o src/cluster/ant_clustering_mean.o -Isrc/ -o ../pyclustering/core/x64/linux/ccore.so
make[1]: Leaving directory '/opt/pyclustering-0.6.6/ccore'

**Comment by annoviko** [comment]
@pconway11,

As I can see ccore.so is located in '/opt/pyclustering/core/x64/linux/ccore.so' and now it can be found, am I right?

About possible segmentation fault (if 'ccore' library was found), there was segmentation fault for some versions of python that was related to exchange between python part of code and library 'ccore' - https://github.com/annoviko/pyclustering/issues/337 (due to built-in 'ctypes' python library update) The bug was corrected, but not delivered to pyclustering 0.6.x build. Only 'master' branch in repository consists of the correction.

There are several options:
**1.** The first one is to switch of core for xmeans algorithm. For that purpose you need to run xmeans with option 'ccore = False', for example:
```python
xmeans_instance = xmeans(sample, start_centers, ccore = False);
```

In this way clustering will be performed only by python code without using ccore.so. Of course it affect performance, but it works.

**2.** The second is to use 'master' branch from repository. You can install it manually - it is really easy:
```bash
# Download pyclustering
$> mkdir pyclustering
$> cd pyclustering
$> git clone https://github.com/annoviko/pyclustering.git .

# Setup pyclustering
$> sudo python3 setup.py install
```
And try to use xmeans algorithm again using ccore.

**Comment by pconway11** [comment]
Thanks Andrei ...using master branch worked perfectly

**Comment by annoviko** [comment]
@pconway11, you're welcome! I am glad to hear that it works.
