### ISSUE TITLE
[pyclustering.cluster.rock] Use ROCK for clustering data set.

### ISSUE THREAD

**Issue by NaserMonsefi** [annoviko/pyclustering#373]
Hi,

I am trying to use the Robust Clustering Algorithm for Categorical Attributes (ROCK) algorithm on a data set containing categorical attributes but getting an error that data can not be `str`. How can I use this method with categorical data set.

Thanks,
Naser

**Comment by annoviko** [comment]
Hello, @NaserMonsefi ,

ROCK implementation in the library does not support categorical data, it was adapted and implemented for data that can be defined as coordinates, for example: [ [ 0.1, 0.2 ], [0.5, 0.2], [6.7, 6.8], [6.9, 6.1] ]. Input data for the algorithm (as well as for others in the library) should be represented by list of points (list of coordinates) as it was presented above.

Thus, you need to transform your data before algorithm usage.

**Comment by NaserMonsefi** [comment]
Thanks for your quick respond @annoviko 
By transforming data, do you mean creating dummy variables similar to how `rockCluster` in `r` 'cba' package deal with categorical data?

**Comment by annoviko** [comment]
@NaserMonsefi ,

I am sorry, but I am not familiar with 'r' and can't say much. By transforming I mean that you need to adapt your dataset for the algorithm to make it possible to use it.

For example, you have following data ['White', 'Grey', 'White', 'Light Grey', 'Red', 'Black'], so you need to transform it to numerical representation and representation is up to you, for example, it can be RGB, where 'White' = [255, 255, 255], Black = [0, 0, 0]. Or grey representation, where for example 'White' = [ 0 ], 'Red' = [ 0.5 ], 'Black' = [ 1 ].

**Comment by NaserMonsefi** [comment]
No worries, that would be similar to dummy variables used for regression. so if I have `{color=['White', 'Black', 'Red', 'White], shape=['Circle', 'Square', 'Square', 'Circle']}` it will become `{color_White=[1,0,0,1], color_Red=[0,0,1,0], color_black=[0,1,0,0], shape_Circle=[1,0,0,1], shape_Square=[0,1,1,0]}`. Would this work?

**Comment by annoviko** [comment]
@NaserMonsefi ,

In this case it should be as follows: [ [1, 0, 0, 1], [0, 0, 1, 0], [0, 1, 0, 0], [1, 0, 0, 1], [0, 1, 1, 0] ]. But I would introduce additional coordinate in your case, because shapes are to close to colors. For example, 10 for colors and 100 for shapes: [ [10, 1, 0, 0, 1], [10, 0, 0, 1, 0], [10, 0, 1, 0, 0], [100, 1, 0, 0, 1], [100, 0, 1, 1, 0] ].

**Comment by avantika-banerjee** [comment]
Hello, 
I was trying to cluster categorical dataset and like @NaserMonsefi faced the same issue; now, this surprises me a little that there is no way of handling such datasets as it is (as described in many research papers). 
I would have hot encoded the data as discussed above but is it advised to do so? Doesn't the data lose its essence?

**Comment by annoviko** [comment]
Hello, @avantika-banerjee,
If your encoding is sensible then you can expect proper clustering results.

**Comment by avantika-banerjee** [comment]
Hey,
`If your encoding is sensible`, could you please explain this further? I have five attributes:
attribute_1 has 82 distinct values
attribute_2 has 21 distinct values
attribute_3 has 3 distinct values
attribute_4 has 2 distinct values
attribute_5 has 4 distinct values

Thank you! @annoviko
