### ISSUE TITLE
unable to pip install 0.7.1 source tarball from pypi

### ISSUE THREAD

**Issue by ran404** [annoviko/pyclustering#377]
The recently uploaded 0.7.1 tarball in pypi doesn't work with pip install, see below. The problem is that the tgz is missing the PKG-INFO.rst file, as well as a number of other files. Please can you upload a new version that fixes this issue?

```bash
$ pip install pyclustering --upgrade
Collecting pyclustering
  Downloading pyclustering-0.7.1.tar.gz (1.4MB)
    100% |████████████████████████████████| 1.4MB 598kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-pszvdacz/pyclustering/setup.py", line 59, in <module>
        long_description = load_readme(),
      File "/tmp/pip-build-pszvdacz/pyclustering/setup.py", line 50, in load_readme
        with open('PKG-INFO.rst') as file_descr:
    FileNotFoundError: [Errno 2] No such file or directory: 'PKG-INFO.rst'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-pszvdacz/pyclustering/
```

**Comment by annoviko** [comment]
Hello, @ran404 , thank you for the notification, I will upload the corrected version ASAP.

**Comment by annoviko** [comment]
@ran404 , I have uploaded corrected version, could you please try install the library again?

**Comment by ran404** [comment]
@annoviko , I can confirm that the new version 0.7.2 now works properly with pip install --upgrade, thank you very much!

**Comment by annoviko** [comment]
@ran404 , you're welcome and thank you for bug reporting!
