### ISSUE TITLE
[pyclustering.cluster.clique] CLIQUE: Grid-Based Subspace Clustering

### ISSUE THREAD

**Issue by annoviko** [annoviko/pyclustering#381]
**Introduction**
CLIQUE is a density-based and grid-based subspace clustering algorithm. Python implementation of the algorithm is required in pyclustering.

**Resources**
1. Lecture: https://www.coursera.org/learn/cluster-analysis/lecture/AAHTA/5-6-clique-grid-based-subspace-clustering
2. Brief description on slides: https://www.slideshare.net/sk_klms/clique
3. Article: Automatic subspace clustering of high dimensional data for data mining applications. In Proc. of 1998 ACM SIGMOD

**Description**
File source location: pyclustering/cluster/clique.py
Class name: clique
Interface of the class:
```python
class clique:
    def __init__(<input parameters of the algorithm>):
        # initialization
    
    def process():
        # algorithm implementation
    
    def get_clusters():
        # return clustering result as list of indexes, for example
        # [ [0, 1, 2, 3], [4, 5, 6, 7] ].
```

Some specific for the algorithm information should be also displayed via additional methods.

**Requirements**
- Algorithm implementation;
- Whole code should have doxygen comments;
- Switch on the source code to document generation (docs/doxygen_conf_pyclustering);
- Unit-tests for the algorithm should be written (pyclustering/cluster/tests/unit/ut_clique.py);
- Examples of clustering algorithm should be written (pyclustering/cluster/examples/clique_examples.py);

Optional (investigation is required before implementation):
Specific visualizer for the algorithm to display clustering results as follows (image from article):
```python
class clique_visualizer:
    def visualize():
        # cluster visualization for 2D and 3D
```
![clique](https://user-images.githubusercontent.com/6785869/32099921-ed928af4-bb1a-11e7-8003-f7718a144b3c.png)

**Comment by Datamined** [comment]
Hello, thanks for your fantastic package.
Any progress with this method? Any ETA of release date?

**Comment by annoviko** [comment]
Hello, @Datamined ,
It is planned to be in release 0.9.0 that will be at the end of February - beginning of March.

**Comment by farzanullah** [comment]
In clique, whenever i try to run code with 9 or more dimensions, it gives the error:

OSError: [WinError -529697949] Windows Error 0xe06d7363

What could be the reason for this?

**Comment by annoviko** [comment]
Hi @farzanullah ,

Could you please provide version of the library and code example how do you use this algorithm? Does it work with data with 8 dimensions?
