### ISSUE TITLE
about graph format

### ISSUE THREAD

**Issue by mortunco** [annoviko/pyclustering#391]
Hi,

Sorry for my ignorant question but is there a way that  could you explain the graph format little bit.( the ones that have .grpr extension in the sample/ dir.

I have an external dataset that i wanna apply random colouring.(Dsatur). I need to put my input into your methods format.( I have a node file which contains the node weights and edge file that contain edge connectivity info between nodes).

For ex; is pyclustering.dstatur compatible with previously published graph libraries such as igraph ? or any of them.

Any information will save my life through my thesis.

Best regards,

Tunc.

**Comment by annoviko** [comment]
Hello, @mortunco ,

It's pretty simple format, it is based on some format (with my little extensions) that I have found for testing graph coloring algorithms.

Let's consider **GraphSimple1.grpr**.
c - means comments, algorithm ignore this line when it sees 'c' at the beginning.
m - means that connectivity matrix is used for graph representation.
```
m 0 0 1 0 0   <--- the first node has connection to the third
m 0 0 0 1 0   <--- [2] has connection to [4]
m 1 0 0 1 1   <--- [3] has connection to [1], [4] and [5]
m 0 1 1 0 0   <--- [4] has connection to [2], [3]
m 0 0 1 0 0   <--- [5] has connection to [3]
```
r - means spatial representation in data-space - it is used for graph visualization only and can be omitted.

But you can use edge representation, using 'e', and list (vector) representation using 'v'.

Usage example can be found here: **pyclustering\gcolor\examples\dsatur_examples.py**

**Comment by mortunco** [comment]
Thank you very much for explanation. I think I will focus on the matrix one. 

thanks for the fast response as well.

Best,

T.
