### ISSUE TITLE
question about som_sc

### ISSUE THREAD

**Issue by jnuvenus** [annoviko/pyclustering#405]
Hello, I'm testing  testing your implementation of som_sc and sync_som algorithm in my work, and I have some question about the som_sc. Why we should allocate number of clusters? In some papers, the som algorithm used in clustering can be seen as an  unsupervised learning method.

**Comment by annoviko** [comment]
Hello, @jnuvenus,

Thank you for your question! SOM-SC is a simple clustering SOM based algorithm and I would say it is the simplest SOM based algorithm. Here, neurons behave as centers in K-Means. Amount of clusters defines amount of neurons. There are a lot of algorithms based on SOM that are much more intellectual and smarter, but this one works like this - using amount of clusters as an input parameter. Clustering results are close to K-Means, thus, SOM-SC is not able to process correctly elongated clusters that are close to each other, like DBSCAN or CURE.

**Comment by annoviko** [comment]
@jnuvenus, additionally I would like to write that if you are interested in SOM (Self-Organized Feature Map) itself, you can find it in 'pyclustering.nnet.som'. SOM-based algorithms in module 'pyclustering.cluster' are adapted for cluster analysis and provide more specific programming interface. But for unsupervised learning you need to use SOM itself (for example, to implement your own or existed SOM-based algorithm or method) - 'pyclustering.nnet.som'. SOM usage examples can be found here:
- pyclustering/nnet/examples/som_examples.py - various examples with visualization.
- pyclustering/nnet/examples/som_recognition.py - pattern recognition (digits from '0' to '9').

**Comment by jnuvenus** [comment]
Thank you, I will try your suggestion。
