### ISSUE TITLE
Bug: can't cluster simple data without ccore=True

### ISSUE THREAD

**Issue by Jeff-Tian** [annoviko/pyclustering#407]
```
x = xmeans([[0],[0],[10],[10],[20],[20]],[[5],[20]], 20, 0.025)
x.process()
```
throws: ValueError: math domain error
But if turn on ccore = True, then the result is correct:
```
x = xmeans([[0],[0],[10],[10],[20],[20]],[[5],[20]], 20, 0.025, ccore=True)
x.process()
```

**Comment by annoviko** [comment]
@Jeff-Tian, thank you for the bug reporting and code example. It's a definitely bug that will be corrected soon.

**Comment by annoviko** [comment]
@Jeff-Tian, I have corrected it on '0.8.dev' branch. It works for 'CCORE' because 'std::log(x)' is able to perform calculation for values that are less or equal to zero:
```C++
double value = std::log(0); /* equals to '-inf' */
```

But it does not work for Python - exception is thrown instead.

**Comment by Jeff-Tian** [comment]
Wow, checked it and it works now! Thank you for so quickly turnaround.

**Comment by annoviko** [comment]
@Jeff-Tian, if you are going to use '0.8.dev' - it a development branch. So, you need to build CCORE by yourself. For linux:
```bash
cd pyclustering/ccore
make ccore_x64 # if you are working on x64
make ccore_x86 # if you are working on x86
```

And for windows using visual studio project 2015: **pyclustering\ccore\ccore.sln**

**Comment by Jeff-Tian** [comment]
@annoviko, thank you for the information! Yesterday I just checked out '0.8.dev' branch and run the python version very well. If later I need to build a CCORE I will reference the information you provided.
