### ISSUE TITLE
kmedians error in update medians Python 2

### ISSUE THREAD

**Issue by animecomico** [annoviko/pyclustering#415]
Hi, 

The algorithm of Kmedians not work in **version 0.7.2** with python 2.
In file **kmedians.py line 192**
 relative_index_median = math.floor(length_cluster / 2);
**Should be:**
 **relative_index_median = int(math.floor(length_cluster / 2));**

**Comment by annoviko** [comment]
Hello, @animecomico,

Thank you for your bug report, I will add this change to the code of kmedians. But also I would like to underline that pyclustering is not supported for Python 2, only for Python 3.4 or greater, so currently you can use this algorithm as it is on Python >= 3.4.

**Comment by annoviko** [comment]
@animecomico, 

The correction for the problem is available on branch '0.8.dev'. Thank you again for your report!
