### ISSUE TITLE
K medoids implementation for sentences

### ISSUE THREAD

**Issue by batrabhumika1992** [annoviko/pyclustering#420]
Can I use k medoids algorithm for sentences, if yes please explain how as I am new to python

**Comment by annoviko** [comment]
Hello, @batrabhumika1992,

Yes, you can use k-medoids algorithm for sentence clustering. It is all depending on sentence encoding - pattern preparation, and task requirement, for example, using mining encoding for clustering by mining. In this case you need to convert your sentences to mining vectors by some method, for example, using simple method N-gram. In other words, you need to prepare your sentences for clustering, but clustering itself will be almost the same:
```python
# encode your sentence by some method
encoded_sentences = encode_somehow(sentences);

# prepare initial required amount of medoids, for example, using kmeans_plus_plus initializer:
amount_medoids = 5;    # for example you have five minings only.
initial_centers = kmeans_plusplus_initializer(sample, amount_medoids).initialize();
initial_medoids = [];
for center in centers:
    initial_medoids.append(centers.index(center));

# create K-Medoids algorithm
kmedoids_instance = kmedoids(encoded_sentences , initial_medoids);

# Start processing and obtain clusters
kmedoids_instance.process();
clusters = kmedoids_instance.get_clusters();
```

Link to N-gram: https://en.wikipedia.org/wiki/N-gram
