### ISSUE TITLE
Kmedoids with distance_matrix - list index out of range

### ISSUE THREAD

**Issue by miguel-ribeiro** [annoviko/pyclustering#425]
While using kmedoids with the parameter data_type='distance_matrix' and a square matrix, I'm receiving the following error:

File "...Python36-32\lib\site-packages\pyclustering\cluster\kmedoids.py", line 158, in process
    self.__clusters = self.__update_clusters();
  File "...\Python36-32\lib\site-packages\pyclustering\cluster\kmedoids.py", line 238, in __update_clusters
    dist = self.__distance_calculator(index_point, self.__medoid_indexes[index]);
  File "...\Python36-32\lib\site-packages\pyclustering\cluster\kmedoids.py", line 214, in <lambda>
    return lambda index1, index2: self.__pointer_data[index1][index2];
IndexError: list index out of range

**Comment by annoviko** [comment]
@miguel-ribeiro ,

Thank you for reporting. Could you please provide type of distance matrix that were used? Is it list of lists? Or is it numpy.matrix?

**Comment by miguel-ribeiro** [comment]
Ok, I have tried so much stuff that got confused. I found out that I was testing with a non-square distance matrix (my fault)
Now that I made it square, it no longer complains about the index, but complains about:

> pyclustering core is not found (expected core location: 'C:\Users\xxxxx\AppData\Local\Programs\Python\Python36\lib\site-packages\pyclustering\core\x64\win\ccore.dll').
> Probably library has not been successfully installed ('win32', '64bit').
> 

I installed this using this git version with "python setup.py install" with no errors.
Though when I had installed the 0.8.0 version available from pip, and then I update it with the latest version from git, it retains the ccore.dll files, but now gives a different error:

> AttributeError: function 'metric_create' not found
> Exception ignored in: <bound method metric_wrapper.__del__ of <pyclustering.core.metric_wrapper.metric_wrapper object at 0x00000226FF48EF98>>
> Traceback (most recent call last):
>   File "C:\Users\miguel\AppData\Local\Programs\Python\Python36\lib\site-packages\pyclustering\core\metric_wrapper.py", line 52, in __del__
>     if self.__pointer:
> AttributeError: 'metric_wrapper' object has no attribute '_metric_wrapper__pointer'

**Comment by annoviko** [comment]
@miguel-ribeiro ,

When you download pyclustering using pip - you obtains the last official release, currently it is 0.8.0. It contains core of the library that is already built. But when you are using GitHub repository - you have version under development that is not released yet. All changes related to distance matrix will be available in the next release 0.8.1.

If you want to use version from github you need to build core. In case of linux and 64-bit python:
```bash
cd pyclustering/ccore
make ccore_x64
```

In case of linux and 32-bit:
```bash
cd pyclustering/ccore
make ccore_x86
```

In case of linux and you don't know what kind of version is required (but be ready to install additional gcc libraries to support multi-platform compilation if they are not installed yet):
```bash
cd pyclustering/ccore
make ccore
```

In case of windows:
1. Open folder pyclustering/ccore;
2. Open MSVS2015 solution: ccore.sln;
3. Choose platform (x86 or x64);
4. Build 'ccore' project;

Currently, you are using the latest python code of the library, but core is still from 0.8.0 that was obtained from pip. You need to rebuild it and it will resolve your problems.

**Comment by miguel-ribeiro** [comment]
Many thanks!
I used the latest, because I needed a distance matrix with the hamming distances.

**Comment by annoviko** [comment]
@miguel-ribeiro ,

Your welcome! Also you can force to use python implementation by setting flag 'ccore' to False:
```python
kmedoids_instance = kmedoids(input_data, initial_medoids, ccore=False);
kmedoids_instance.process();
```
