### ISSUE TITLE
Anyway to lose the matplotlib dependency or make it optional?

### ISSUE THREAD

**Issue by awhillas** [annoviko/pyclustering#455]
I'm getting the following:
```
Traceback (most recent call last):
  File "/Users/alex/dev/something/extractor/ml.py", line 8, in <module>
    from pyclustering.cluster.kmeans import kmeans
  File "/Users/alex/dev/venv/content-extractor-3pp1FAW1/lib/python3.6/site-packages/pyclustering/cluster/__init__.py", line 26, in <module>
    import matplotlib.pyplot as plt;
  File "/Users/alex/dev/venv/content-extractor-3pp1FAW1/lib/python3.6/site-packages/matplotlib/pyplot.py", line 115, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/Users/alex/dev/venv/content-extractor-3pp1FAW1/lib/python3.6/site-packages/matplotlib/backends/__init__.py", line 62, in pylab_setup
    [backend_name], 0)
  File "/Users/alex/dev/venv/content-extractor-3pp1FAW1/lib/python3.6/site-packages/matplotlib/backends/backend_macosx.py", line 17, in <module>
    from matplotlib.backends import _macosx

RuntimeError: Python is not installed as a framework. The Mac OS X
backend will not be able to function correctly if Python is not
installed as a framework. See the Python documentation for more
information on installing Python as a framework on Mac OS X. Please
either reinstall Python as a framework, or try one of the other
backends. If you are using (Ana)Conda please install python.app and
replace the use of 'python' with 'pythonw'. See 'Working with
Matplotlib on OSX' in the Matplotlib FAQ for more information.
```
Don't need plotting, just the clusters :-/
Perhaps move the
```
import matplotlib.pyplot as plt;
import matplotlib.gridspec as gridspec;
```
inside the `show()` function?

**Comment by annoviko** [comment]
Hello,

'kmeans' module contains visualization tool 'kmeans_visualizer' that uses matplotlib functionality to visualize clustering process and clustering results that are specific for K-Means. In other words, 'kmeans' won't be load without matplotlib module, you need to install matplotlib to resolve this issue.

**Comment by kuzeko** [comment]
Hi, I concur with the idea to at remove the `matplotlib` dependency (see [this scikit-optimize issue for some discussion](https://github.com/scikit-optimize/scikit-optimize/issues/637)

Below the current error on macOS, even with `matplotlib` installed.

```bash
$ pipenv install matplotlib
[... installed] 

$ pipenv install pyclustering
[... installed] 

$ pipenv shell
[... virtualenv activated] 

$ python3
Python 3.7.0 (default, Oct  2 2018, 09:18:58) 
[Clang 10.0.0 (clang-1000.11.45.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyclustering.cluster.kmedoids import kmedoids;
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kuzeko/.local/share/virtualenvs/TEST-pyTfwz7A/lib/python3.7/site-packages/pyclustering/cluster/__init__.py", line 26, in <module>
    import matplotlib.pyplot as plt;
  File "/Users/kuzeko/.local/share/virtualenvs/TEST-pyTfwz7A/lib/python3.7/site-packages/matplotlib/pyplot.py", line 2374, in <module>
    switch_backend(rcParams["backend"])
  File "/Users/kuzeko/.local/share/virtualenvs/TEST-pyTfwz7A/lib/python3.7/site-packages/matplotlib/pyplot.py", line 207, in switch_backend
    backend_mod = importlib.import_module(backend_name)
  File "/Users/kuzeko/.local/share/virtualenvs/TEST-pyTfwz7A/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/kuzeko/.local/share/virtualenvs/TEST-pyTfwz7A/lib/python3.7/site-packages/matplotlib/backends/backend_macosx.py", line 14, in <module>
    from matplotlib.backends import _macosx
ImportError: Python is not installed as a framework. The Mac OS X backend will not be able to function correctly if Python is not installed as a framework. See the Python documentation for more information on installing Python as a framework on Mac OS X. Please either reinstall Python as a framework, or try one of the other backends. If you are using (Ana)Conda please install python.app and replace the use of 'python' with 'pythonw'. See 'Working with Matplotlib on OSX' in the Matplotlib FAQ for more information.
>>>  
```

**Comment by annoviko** [comment]
@kuzeko,
In line with error description you have some troubles with matplotlib on MAC OS:

> ImportError: Python is not installed as a framework. The Mac OS X backend will not be able to function correctly if Python is not installed as a framework. See the Python documentation for more information on installing Python as a framework on Mac OS X. Please either reinstall Python as a framework, or try one of the other backends. If you are using (Ana)Conda please install python.app and replace the use of 'python' with 'pythonw'. See 'Working with Matplotlib on OSX' in the Matplotlib FAQ for more information.

Try to follow recommendations that are displayes, probably it helps to resolve the issue.

**Comment by kuzeko** [comment]
Thanks, I know how to solve the problem. My point is that, since I only want to do clustering, not to plot, I should not have to fix that error, i.e., would be better for the method not to require the installation of `matplotlib` and `pillow`.

If you look here https://github.com/scikit-optimize/scikit-optimize/pull/639
you'll see an alternative way to deal with this matplotlib requirement, that is also in line with @awhillas problem and suggestion, i.e., do not require matplotlib.

**Comment by annoviko** [comment]
@kuzeko, that make sence. pyclustering provides clustering algorithms and visualizer how them, to make clustering animation or just visualize clustering results and all these tools based on matplotlib - that is a reason why pyclustering uses matplotlib. I have already have solution how to deal with that problem - get rid of matplotlib dependency if someone needs to perform cluster analysis only. Thank you for your vision of the problem.

I have created new task for that problem: https://github.com/annoviko/pyclustering/issues/472 .

**Comment by kuzeko** [comment]
Thanks for considering this enhacement!
P.s, if people using macOS have a similar problem, the workaround is the following:

```bash
$ pipenv install pillow

$ pipenv shell

$ python3
Python 3.7.0 (default, Oct  2 2018, 09:18:58) 
[Clang 10.0.0 (clang-1000.11.45.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import matplotlib
>>> matplotlib.use('PS')
>>> from pyclustering.cluster.kmedoids import kmedoids
```

**Comment by annoviko** [comment]
@kuzeko , the changes has been introduced and they are available on the branch '0.8.dev' and will be available in the next release.

**Comment by kuzeko** [comment]
That's great! Thanks.
Looking forward to test them.

Question:  should `from PIL import Image` get the same treatment?

**Comment by annoviko** [comment]
@kuzeko , yes, I agree, it should be also covered by the same try-except block with appropriate warning message. I will provide required changes.

**Comment by annoviko** [comment]
Have done the same for PIL (Pillow).
