### ISSUE TITLE
Error in medoids computations

### ISSUE THREAD

**Issue by bamal** [annoviko/pyclustering#480]
I am trying to compute medoids for a 3D matrix coordinates. The coordinates of medoids were wrong for sure so I though that it would help to convert 3D coordinates to 1D coordinates and take as input for the `medoids` method a list of 1Dcoordinates (e.g., [2000, 3002, 3455]). I think each value here may be considered as a data point as in your `sample07.data`, However, I am getting a bug as the medoid of the input list is not within these points.

May I missing something please ?

**Comment by annoviko** [comment]
Here you can find usage example: https://pyclustering.github.io/docs/0.8.2/html/d0/dd3/classpyclustering_1_1cluster_1_1kmedoids_1_1kmedoids.html

**Comment by bamal** [comment]
@annoviko  it is working for 3D data. All my thanks for the quick and clear response !
