### ISSUE TITLE
Faster custom metric kmeans

### ISSUE THREAD

**Issue by MilanCugur** [annoviko/pyclustering#482]
First of all, gread job! Your library is awesome.

Is there any way to use cpp boosting with custom metric for your kmeans implementation?

When I specify my custom metric for your kmeans, its too slow!
I cant use numpy:
>if self.__metric.get_type() != type_metric.USER_DEFINED:
>    self.__metric.enable_numpy_usage()
> else:
>    self.__metric.disable_numpy_usage()

And also cant use cpp boosting:

> self.__ccore = ccore and self.__metric.get_type() != type_metric.USER_DEFINED
>          if self.__ccore is True:
>             self.__process_by_ccore()
>         else:
>             self.__process_by_python()

But __process_by_python() is reall slow for my task.

Thanks in advance,
Milan

**Comment by annoviko** [comment]
Hello, @MilanCugur,
Thank you for your report, that means that it is time to increase priority of the following issue #422. There is crash on some platforms when C++ implementation calls user defined metric. I will investigate the problem and find out solution. But also I have another one question, what is metric used in your case? As a workaround I have tried to provide most well-known metrics, probably I have missed something.

**Comment by MilanCugur** [comment]
Hello @annoviko, thanks you for your fast reply!
.
Your list of metrics is extensive and covers all the main things, but I have an idea to try chi square metrics for my clustering. 
This fashion of clustering, I want to code is similar to http://www.btluke.com/clusdis.html.

There are also a couple of scientific papers published on this topic.
When can I expect the update? Can I help in some way?

**Comment by annoviko** [comment]
@MilanCugur, I have introduced Canberra and Chi square distances to the library. They are available on master branch and will be available in the next release 0.9.0. You need to build library's core using sources, there is instruction how to do that: https://github.com/annoviko/pyclustering/wiki/Core-of-the-PyClustering .

If you have any questions or troubles related to pyclustering, do not hesitate to ask them :-) .
