### ISSUE TITLE
Kmeans++ incorrect distance calculation when the return_index keyword argument is True

### ISSUE THREAD

**Issue by metinsuloglu** [annoviko/pyclustering#485]
The `__calculate_shortest_distances` method in the Python class `center_initializer.py` assumes the "center" argument contains a list of coordinate points as vectors, however the `initialize()` method may send a list of indices. When the `return_index` argument is True, this leads to incorrect euclidean distance calculations.

**Comment by annoviko** [comment]
Hello, @metinsuloglu!
I have checked the code and I agree this is a bug. I will provide correction for the problem.

**Comment by annoviko** [comment]
The correction is available on 'master' branch. And will be available in release 0.9.0.
