### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by adavidzh** [annoviko/pyclustering#492]
Somehow [this line in `README.rst` is broken](https://github.com/annoviko/pyclustering/blame/506deb69fcb3e66b61c938055886f44f35283c93/README.rst#L73). It should probably be `cd ccore`.

**Comment by annoviko** [comment]
@adavidzh , instructions are updated for 0.8.2.rel and for master branch.

**Comment by adavidzh** [comment]
Thanks.

**Comment by adavidzh** [comment]
This is part of the review at https://github.com/openjournals/joss-reviews/issues/1230.
