### ISSUE TITLE
Example in README

### ISSUE THREAD

**Issue by adavidzh** [annoviko/pyclustering#493]
[One example in `README.rst`](https://github.com/annoviko/pyclustering/blame/a201fb7ca11a3d5637984e4d157e6b50ef3d9234/README.rst#L275) seems to depend on an undefined argument.

This should be rewritten to work out of the box.

**Comment by adavidzh** [comment]
Also the last example does not work out of the box because of [`SIMPLE_SAMPLES.SAMPLE_SIMPLE1`](https://github.com/annoviko/pyclustering/blame/a201fb7ca11a3d5637984e4d157e6b50ef3d9234/README.rst#L297) not being defined.

**Comment by annoviko** [comment]
Hello, @adavidzh,
README is updated: examples are rechecked, updated, and several new examples are added.

**Comment by adavidzh** [comment]
This is much better, thanks!

Right now there is one problem on the OPTICS example. It looks like there is a `optics_instance.process()` missing since at the end of it we're just getting nothing:
```
>>> list(map(lambda x:type(x), [clusters,noise]))
[<class 'NoneType'>, <class 'NoneType'>]
```

It would also be nice if there were a visualization for the result, which I would not know exactly how to add.

**Comment by annoviko** [comment]
@adavidzh , yes, you are correct, I have updated OPTICS example for 'master' and '0.8.2.rel':
```python
from pyclustering.cluster import cluster_visualizer
from pyclustering.cluster.optics import optics, ordering_analyser, ordering_visualizer
from pyclustering.samples.definitions import FCPS_SAMPLES
from pyclustering.utils import read_sample

# Read sample for clustering from some file
sample = read_sample(FCPS_SAMPLES.SAMPLE_LSUN)

# Run cluster analysis where connectivity radius is bigger than real
radius = 2.0
neighbors = 3
amount_of_clusters = 3
optics_instance = optics(sample, radius, neighbors, amount_of_clusters)

# Performs cluster analysis
optics_instance.process()

# Obtain results of clustering
clusters = optics_instance.get_clusters()
noise = optics_instance.get_noise()
ordering = optics_instance.get_ordering()

# Visualize ordering diagram
analyser = ordering_analyser(ordering)
ordering_visualizer.show_ordering_diagram(analyser, amount_of_clusters)

# Visualize clustering results
visualizer = cluster_visualizer()
visualizer.append_clusters(clusters, sample)
visualizer.show()
```

**Comment by adavidzh** [comment]
Great, thanks.

**Comment by adavidzh** [comment]
This is part of the review at https://github.com/openjournals/joss-reviews/issues/1230.
