### ISSUE TITLE
[pyclustering.cluster.kmedoids]: add stop condition 'max_iterations'

### ISSUE THREAD

**Issue by EggsBenedict** [annoviko/pyclustering#496]
The kmedoids algorithm in practice seems to converge pretty quickly, but since the centroid can potentially jump around a big distance as it moves from point to point and not a mean distance (like with kmeans) the stop condition of `tolerance` might not catch when a centroid is jumping between one point and the other, right? Perhaps a `max_iterations` argument might be better than tolerance? I would think that kmeans and kmedians might also benefit from this secondary catch.

**Comment by annoviko** [comment]
Hello, @EggsBenedict ,

Thank you for your proposal! I was thinking about that too, it good idea to add this feature for **kmeans**, **kmedoids** and **kmedians**. I will implement this feature for these algorithms and it will be available in the next release - 0.9.0.

**Comment by EggsBenedict** [comment]
Excellent! Thanks for the great implementation and response @annoviko

**Comment by annoviko** [comment]
@EggsBenedict , proposed changes are introduced and they are available on 'master' and '0.9.dev' branches. They will available in the next release - 0.9.0.
