### ISSUE TITLE
How to use pyclustering kmedoids using gower distance matrix?

### ISSUE THREAD

**Issue by zahs123** [annoviko/pyclustering#499]
Hi, 

Not sure if this has already been asked but I have a dataframe consisting of categorical and numerical data. I want to cluster this data to extract features. I use the following code from https://sourceforge.net/projects/gower-distance-4python/files/ to calculate the gower distance. 

My code is as follows: 

```
`import pyclustering 

from sklearn.metrics.pairwise import pairwise_distances
import numpy as np    
from pyclustering.cluster.kmedoids import kmedoids;
from pyclustering.utils import read_sample;
from pyclustering.cluster.center_initializer import kmeans_plusplus_initializer
from pyclustering.cluster.elbow import elbow
from pyclustering.cluster.kmeans import kmeans
from pyclustering.cluster.encoder import cluster_encoder, type_encoding

D = gower_distances(filtOrdersGower_subset)
initial_medoids = kmeans_plusplus_initializer(D, 4).initialize(return_index=True)
kmedoids_instance = kmedoids(D,initial_medoids, data_type='distance_matrix');

kmedoids_instance.process();
clusters = kmedoids_instance.get_clusters();
`
```
how do i plot these clusters/ get what features in my data are most important? New to pyclustering @annoviko

**Comment by annoviko** [comment]
@zahs123 ,

Have you got non-distance matrix data? Is 'filtOrdersGower_subset' common data, where each object is represented by array of coordinates, for example, data = [p1, p2, p3, ...,], where p1 = [0.1, 0.5], p2 = [0.1, 0.7] and so on?

If yes than you can do something like this:
```python
from pyclustering.samples.definitions import SIMPLE_SAMPLES
from pyclustering.cluster import cluster_visualizer
from pyclustering.cluster.center_initializer import kmeans_plusplus_initializer
from pyclustering.cluster.kmedoids import kmedoids
from pyclustering.utils import read_sample

# load list of points for cluster analysis
sample = read_sample(SIMPLE_SAMPLES.SAMPLE_SIMPLE3)

# initialize
initial_medoids = kmeans_plusplus_initializer(sample, 4, kmeans_plusplus_initializer.FARTHEST_CENTER_CANDIDATE).initialize(return_index=True)

# create instance of K-Medoids algorithm
kmedoids_instance = kmedoids(sample, initial_medoids)

# run cluster analysis and obtain results
kmedoids_instance.process()
clusters = kmedoids_instance.get_clusters()
medoids = kmedoids_instance.get_medoids()

# visualize clustering results
visualizer = cluster_visualizer(1)
visualizer.append_clusters(clusters, sample, 0)
visualizer.append_cluster([sample[index] for index in initial_medoids], marker='*', markersize=15)
visualizer.append_cluster(medoids, data=sample, marker='*', markersize=15)
visualizer.show()
```

**Comment by zahs123** [comment]
@annoviko filtOrdersGower_subset is a dataframe containing 10,000 rows of categorical data e.g. column one is type of trade, column two is type of asset.. I then converted this to a distance matrix where it is symmetrical around the diagonal using 'Gower Distance' function from link provided. Not sure how best to go about clustering data when it is **categorical**.. so no i guess my data is not in that format. Do you know how I should go about this?

**Comment by annoviko** [comment]
@zahs123 , I think you need to dig a little in the data visualization, probably you will find some techniques to visualize distance matrix without knowledge about coordinates, for example, heatmap or something else.

There are some information related to distance matrix visualization, so probably this link would be useful: https://stackoverflow.com/questions/3081066/what-techniques-exists-in-r-to-visualize-a-distance-matrix .

**Comment by zahs123** [comment]
@annoviko i thought kmedoids could take a symmetric distance matrix?

**Comment by annoviko** [comment]
@zahs123 , yes, that's right, it accepts distance matrix for clustering.

**Comment by zahs123** [comment]
@annoviko  ok it's just above in my question 'D ' is a distance matrix i pass through using the gower function, so i could use what you have written above?

**Comment by annoviko** [comment]
@annoviko, yes, you can, but you need to modify your code. This is an update example with distance matrix:
```python
from pyclustering.samples.definitions import SIMPLE_SAMPLES
from pyclustering.cluster import cluster_visualizer
from pyclustering.cluster.center_initializer import kmeans_plusplus_initializer
from pyclustering.cluster.kmedoids import kmedoids
from pyclustering.utils import read_sample, calculate_distance_matrix

# load list of points for cluster analysis
sample = read_sample(SIMPLE_SAMPLES.SAMPLE_SIMPLE3)
matrix = calculate_distance_matrix(sample)

# initialize
initial_medoids = kmeans_plusplus_initializer(sample, 4, kmeans_plusplus_initializer.FARTHEST_CENTER_CANDIDATE).initialize(return_index=True)

# create instance of K-Medoids algorithm
kmedoids_instance = kmedoids(matrix, initial_medoids, data_type='distance_matrix')

# run cluster analysis and obtain results
kmedoids_instance.process()
clusters = kmedoids_instance.get_clusters()
medoids = kmedoids_instance.get_medoids()

# visualize clustering results
visualizer = cluster_visualizer()
visualizer.append_clusters(clusters, sample)
visualizer.show()
```

**Comment by Min-eralwater** [comment]
hi @annoviko, I am too, using your gowers_distance algorithm to do clustering. Thank you for all the hardwork. I would also like to seek help for this error that I am encountering:

[[636016589 20.55757 -93.66279000000002 ... 32.2 13.65 70.0]
 [304969000 20.35304 -93.98392 ... 29.8 11.4 nan]
 [345070220 19.48597 -93.59531000000001 ... 24.42 5.0 34.0]
 ...
 [356726000 20.53622 -95.72015000000002 ... 32.26 12.3 70.0]
 [332488706 15.211 -90.00332 ... nan nan nan]
 [142144371 4.5717 -92.73836 ... nan nan nan]]
<class 'numpy.ndarray'>
(32674, 13)

this is the sample that I am using - I'm wondering why I can't use this as a sample for the algorithm - the error thrown out is 'unsupported operand type(s) for -: 'str' and 'str'' - but my output is an array of integer values. Thank you for your help!

**Comment by annoviko** [comment]
Hi @Min-eralwater 

Could you please provide full stack-trace and code example?

**Comment by Min-eralwater** [comment]
```
from pyclustering.cluster import cluster_visualizer
from pyclustering.cluster.center_initializer import kmeans_plusplus_initializer
from pyclustering.cluster.kmedoids import kmedoids
from pyclustering.utils import read_sample, calculate_distance_matrix
# load list of points for cluster analysis
# str_data = zone15_3months.applymap(str)
sample = zone15_3months.to_numpy()
matrix = calculate_distance_matrix(sample)`
```

I entered this in, and got the error below: 

```
TypeError                                 Traceback (most recent call last)
<ipython-input-30-c81b895ca5bc> in <module>()
      1 sample = zone15_3months.to_numpy()
----> 2 matrix = calculate_distance_matrix(sample)
      3 
      4 # initialize
      5 initial_medoids = kmeans_plusplus_initializer(sample, 4, kmeans_plusplus_initializer.FARTHEST_CENTER_CANDIDATE).initialize(return_index=True)

5 frames
/usr/local/lib/python3.6/dist-packages/pyclustering/utils/metric.py in euclidean_distance_square(point1, point2)
    365     distance = 0.0
    366     for i in range(len(point1)):
--> 367         distance += (point1[i] - point2[i]) ** 2.0
    368 
    369     return distance

TypeError: unsupported operand type(s) for -: 'str' and 'str'`

```
I tried mapping it to a string but it doesn't work. May I know what's the type of data that is accepted? I'm assuming that the data accepted should be a pandas df or numpy.array 

many thanks!

**Comment by annoviko** [comment]
@Min-eralwater ,

Only numerical elements are supported (including `numpy.nan` or `float('NaN')`), so sample should be like this:
```
[[1.2, 1.3], [1.6, 0.9], [1.1, 2.3]]
```

Matrix should be represented by `numpy.array` or `list` - in other words a container should support `operator.__getitem__(a, b)` and return an element. Are you sure that you do not have string `str` element in your container?

**Comment by Min-eralwater** [comment]
Hi @annoviko, thank you for the clarification - yes there are some NaN values in my dataset but there shouldn't be any strings - or at least not that I know of. I'll check again and make sure there is isn't any. Thanks a lot!

**Comment by annoviko** [comment]
@Min-eralwater , if you can provide data (or small piece of data where the problem is reproduced) then I can try to check the problem by myself. The data can be attached here or send to pyclustering@yandex.ru .
