### ISSUE TITLE
Predict method

### ISSUE THREAD

**Issue by lachhebo** [annoviko/pyclustering#510]
I know clustering is not the same thing as classfification but in my case, it would be useful to predict in which cluster new data are classified based on the cluster I have created using the pyclustering API on training data. 

Does the API have a way to do that, i mean predicting in which cluster my data belong based on the clusters formed during the training step, especially for the BIRCH algorithm ?

**Comment by annoviko** [comment]
Hello, @lachhebo , currently there is no services, except SOM (self-organized feature map) to perform classification. Using SOM you can try to perform clastering and classification as well, here is an example:
```python
from pyclustering.cluster import cluster_visualizer
from pyclustering.nnet.som import som
from pyclustering.nnet.som import type_conn
from pyclustering.samples.definitions import FCPS_SAMPLES
from pyclustering.utils import read_sample

# Read input data.
sample = read_sample(FCPS_SAMPLES.SAMPLE_HEPTA)

# Create SOM using 7 neurons where each neuron represents one cluster and can be considered as a cluster center.
amount_clusters = 7 # 7 clusters are expected in the data.
network = som(1, amount_clusters, type_conn.grid_four)

# Train SOM during 100 epochs.
epochs = 100
network.train(sample, epochs)

# Obtain clusters.
clusters = network.capture_objects

# Visualize obtained clusters
visualizer = cluster_visualizer()
visualizer.append_clusters(clusters, sample)
visualizer.show()

# Perform classification of some random point.
index_cluster = network.simulate([0.0, 0.15, 0.1])
print("Point belongs to cluster '%d'" % index_cluster)

index_cluster = network.simulate([-2.2, 0.1, 0.6])
print("Point belongs to cluster '%d'" % index_cluster)
```

Console output:
```
Point belongs to cluster '2'
Point belongs to cluster '1'
```
![som_fcps_hepta](https://user-images.githubusercontent.com/6785869/56591837-217f6980-65f2-11e9-8e37-022023c3ea1e.png)

**Comment by lachhebo** [comment]
Thank you for your quick answer.
