### ISSUE TITLE
Kmedoids Index Out of Range Issue

### ISSUE THREAD

**Issue by mohamedzv3** [annoviko/pyclustering#513]
When trying to run kmedoids with a distance matrix, I'm getting either a list index out of range if I use a list of lists, or a the following if I use a numpy array of arrays:

Traceback (most recent call last):
  File "make_clusters.py", line 25, in <module>
    kmedoids.process()
  File "/home/mohamedzv3/.conda/envs/lib/python3.6/site-packages/pyclustering/cluster/kmedoids.py", line 153, in process
    self.__clusters = self.__update_clusters()
  File "/home/mohamedzv3/.conda/envs/lib/python3.6/site-packages/pyclustering/cluster/kmedoids.py", line 238, in __update_clusters
    dist = self.__distance_calculator(index_point, self.__medoid_indexes[index])
  File "/home/mohamedzv3/.conda/envs/lib/python3.6/site-packages/pyclustering/cluster/kmedoids.py", line 214, in <lambda>
    return lambda index1, index2: self.__pointer_data[index1][index2]
IndexError: index 10000 is out of bounds for axis 0 with size 10000

I've confirmed that the lists of lists and the arrows are all rows of 10,000 and so it is a square matrix, so I'm not sure how or why this could be happening.

**Comment by annoviko** [comment]
Hello, @mohamedzv3,

Could you please provide code example? Have you use argument data_type='distance_matrix'? If you input is distance matrix then you need to use this parameter.

Have you used pyclustering from pypi? Or just downloaded it from repository? What is version? And what kind of OS do you use? And I see that core is not used in your case and it means that performance is not the best as it could be.

**Comment by mohamedzv3** [comment]
Hi @annoviko,

It turned out to be an issue with the initial medoids, one of them was out of range because the randint function is inclusive on both ends (dumb mistake on my end), but this was resulting in a seg fault or index out of error in the Python without specifying where exactly it was.
