### ISSUE TITLE
Issues during K means clustering with custom distance

### ISSUE THREAD

**Issue by sourcedexter** [annoviko/pyclustering#514]
I have implemented a custom distance calculation lambda function to perform k means clustering. 
This method takes in two vectors ( vec1 and vec2) . Both of these vectors are numpy arrays with shape (20, ) . 

Here's an example for vec1 and vec2: 
**vec1** = [0.12837841 0.17410645 0.03892719 0.01142581 0.0119627  0.01158701
  0.01189765 0.21076787 0.01203716 0.01143249 0.07725643 0.01173101
  0.01180555 0.15848666 0.01157868 0.01134896 0.01149835 0.01219402
  0.05999295 0.01158464]

**vec2** = [0.01199008 0.01205883 0.01158914 0.01174743 0.01229944 0.01191316
  0.01223255 0.01229845 0.01237599 0.0117543  0.01158818 0.01206123
  0.77267748 0.01197971 0.01190461 0.01166842 0.01182201 0.01253727
  0.01159102 0.01191073]

the response from this method is a numpy.float64 value.
Example: 0.5301296095066765

everything runs fine, but sometimes, I find that the k means algorithm calls the distance method with very weird value for vec1 and vec2. 

I found that for some cases: the shape of vec1 and vec2 is (20, 20) 
So, this means that my distance method no longer returns a distance value of type numpy.float64 . Rather, it returns an array of shape ( 20, ).
example: 
[0.011936   0.01233298 0.01185763 0.01193473 0.01193192 0.01233562
  0.01240236 0.75818491 0.01193629 0.01224091 0.01193129 0.01201292
  0.01201555 0.01169131 0.01201393 0.01209295 0.0121648  0.0121697
  0.01209298 0.02472113]

is this an expected behavior? 
I noticed that sometimes, my custom distance method returns negative values and it shouldn't. I believe that these anomalies (vectors with shape (20, 20) ) that are sent to the distance calculation function are causing them.

**Comment by annoviko** [comment]
Hello, @sourcedexter ,

Sorry for late response. That's true, your metric is also used for changes calculation on each iteration. This calculation is required to check condition to stop clustering process.

**Comment by sourcedexter** [comment]
thanks for the response @annoviko . So, to ensure that the rest of the things that I am doing works fine, I need to ensure the result is >= 0.  

I feel I need to add a check within the custom method to, convert the value to 0 if it is negative. Do you think it is okay to do that?or should I ensure that the values computed should be sent as is since it iusing the metric to perform additional checks.

**Comment by annoviko** [comment]
@sourcedexter, generally, I think it is bad idea to substitute negative values by 0, because if distance is 0 then it complitely similar to cluster center and belongs to it. I would recommend you to use absolute function `abs(distance)`. But it is all up to you because I am not familiar with your particular problem that you are trying to solve.

**Comment by sourcedexter** [comment]
What you said makes sense. I will try and evaluate the best possible route for my use case. Thanks.

**Comment by smazrouee** [comment]
Question.... my data and initial centers are both float. I have: 
   kmedoids_instance = kmedoids(sample, initial_medoidsm data_type='distance_matrix') 

which goes fine. But when I do: kmedoids_instance.process() 

I receive ->  "int expected instead of float"

**Comment by annoviko** [comment]
@smazrouee , could you please provide trace of this error and code that you are using?
- Make sure that sample - is a distance matrix.
- Make sure that initial_medoids should contains point indexes (integer format).
