### ISSUE TITLE
License

### ISSUE THREAD

**Issue by giumas** [annoviko/pyclustering#517]
Any thought on adopting a bit [more friendly](https://www.quora.com/What-are-the-most-restrictive-business-unfriendly-open-source-licenses) license?

For instance:

* [scikit-learn](https://github.com/scikit-learn/scikit-learn/blob/master/COPYING)
* [numpy](https://github.com/numpy/numpy/blob/master/LICENSE.txt)
* [matplotlib](https://matplotlib.org/3.1.0/users/license.html)

**Comment by annoviko** [comment]
Hello, @giumas ,

What kind of restrictions do you have with current license?

**Comment by giumas** [comment]
The GPLv3 criticisms are [known](https://en.wikipedia.org/wiki/GNU_General_Public_License#GPLv3_criticism).

Python has a [GPL-compatible license](https://docs.python.org/3/license.html#history-of-the-software).

**Comment by annoviko** [comment]
@giumas , is it a general proposal? And currently you don't have any troubles with pyclustering usage, do you?

**Comment by giumas** [comment]
> is it a general proposal?

Yes. 

This library is really great! As such, a license aligned with other Python scientific packages might attract more core contributors.

**Comment by annoviko** [comment]
@giumas , Ok, thank you for proposal then. I will study these licenses and will chose one of them for pyclustering.

**Comment by annoviko** [comment]
pyclustering library is going to be distributed under license `BSD-3-Clause` since 0.10.1.
