### ISSUE TITLE
Clustering in more than two feature space

### ISSUE THREAD

**Issue by mehdydousty** [annoviko/pyclustering#518]
Hello,
I am trying to use pyclustering in python to cluster 1500 x 30 (sample x feature);however, I get the below error for BIRCH clustering algorithm :
valueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
I was wondering if you could help me to solve the issue.
Thanks

**Comment by annoviko** [comment]
Hello, @mehdydousty ,

Could you please provide usage example?

**Comment by mehdydousty** [comment]
Thanks for the reply.
I am using the below code:

from pyclustering.cluster.birch import birch
data = ... #a matrix of (1500,30)
birch_instance = birch(data, 4)
birch_instance.process()
clusters = birch_instance.get_clusters()

error:
valueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

Any help would be greatly appreciated.
Thanks

**Comment by annoviko** [comment]
Hello, @mehdydousty ,

Make sure that input data has a 'list' python type. Currently, it looks like that you are using numpy input matrix or numpy array as an input data.
