### ISSUE TITLE
CLIQUE returning 0 clusters

### ISSUE THREAD

**Issue by devshah96** [annoviko/pyclustering#519]
Hello,
I am trying to cluster a dataset with 25000 rows and 2500 columns. However, for any value set for the amount_intervals and density_threshold, I get 0 clusters. Could you help me out with this issue? Also, I have provided a list of list as my input.

Also, this too gives me 0 clusters.
a =  [[0,2],[0,3],[0,1],[0,4]]
clique_instance = clique(a,1,0)
clusters = clique_instance.get_clusters()
print("Amount of clusters:", len(clusters))
Thanks

**Comment by annoviko** [comment]
Hello, @devshah96 ,

That's correct, you need to call `process()` method:
```
a = [[0,2],[0,3],[0,1],[0,4]]
clique_instance = clique(a,1,0)
clique_instance.process()
clusters = clique_instance.get_clusters()
print("Amount of clusters:", len(clusters))
```

**Comment by devshah96** [comment]
Hello @annoviko ,
Thank you for such a quick reply. Even after adding the process statement,the huge dataset consisting of 25000 rows and 2500 columns gives me 0 clusters. I have used the following code where final_clr was a numpy array which was then converted to a list of list.

final_clr = final_clr.tolist()
clique_instance =clique(final_clr,10,0)
clique_instance.process()
clusters = clique_instance.get_clusters()
print("Amount of clusters:", len(clusters))

**Comment by annoviko** [comment]
Hello, @devshah96,
I can try to simulate these data. Anyway, may I ask you to provide at least five rows (attach them as a file)? Just to test what is going on.
