### ISSUE TITLE
issue of :clique of automatic find dense unite

### ISSUE THREAD

**Issue by leqsxt** [annoviko/pyclustering#520]
Hello, i have a question about clique clustering,can help me about this:
         i want to know if the code implement gennerate candidate k dim dense untis using k-1 dimension dense units make self-join?

**Comment by annoviko** [comment]
Hello, @leqsxt ,
This implementation of the algorithm compares amount of points that belong to block with threshold (user input, by default - 0 points). If amount of points in a block is bigger then threshold, then block is considered as a part of cluster.

**Comment by leqsxt** [comment]
Thank you annoviko, i am very appreciate for your reply.
          As you said while dim=4 the code can only give 4dim clusters  and run out two dim pictures  how can i get all the 3 dim (when dim=4 there are 4 3dim subspaces )cluster pictures
