### ISSUE TITLE
RANSAC pointcloud

### ISSUE THREAD

**Issue by rfsch** [annoviko/pyclustering#523]
Privet

very nice library. I am looking for a good implementation of RANSAC to extract the groundplane from a LIDAR pointcloud (from autonomous car). Do you have a RANSAC implementation in your library ?

Thanks

**Comment by annoviko** [comment]
Hello, @rfsch ,
No, pyclustering does not contain this algorithm. Try to check it out in scikit-learn or matlab.

**Comment by rfsch** [comment]
Hello @annoviko 

Thanks.
