### ISSUE TITLE
Not support wxpython ???

### ISSUE THREAD

**Issue by liufsd** [annoviko/pyclustering#524]
```
import numpy as np
import random
import wx
import wx.lib.plot as plot

from pyclustering.utils.metric import distance_metric, type_metric
from pyclustering.cluster.kmeans import kmeans as pyclusteringkmeans

if __name__ == "__main__":
    app = wx.App()
    frame = wx.Frame(parent=None, title='Hello World')
    frame.Show()
    app.MainLoop()
```

if i not import pyclustering, it's run success.

**Comment by annoviko** [comment]
Hello, @liufsd, is there any stacktrace or information that is printed to log?

**Comment by liufsd** [comment]
sorry ， have no any log， so i do not know why！you can test it ‘

**Comment by liufsd** [comment]
They frame app Just not show anything when import this library.

**Comment by liufsd** [comment]
`wxpython` : https://realpython.com/python-gui-with-wxpython/

**Comment by liufsd** [comment]
@annoviko There may be conflicts between your library and wxpython library ?
but i have not found any log when run this code . so i have no any idea about this.
Do you find some reason ?

**Comment by annoviko** [comment]
@liufsd, the problem is located in matplotlib, it does not start because pyclustering loads these:
```python
    import matplotlib.pyplot as plt
    import matplotlib.animation as animation
```

You will have the same problem with following code:
```python
import numpy as np
import random
import wx
import wx.lib.plot as plot

import matplotlib.pyplot as plt
import matplotlib.animation as animation

if __name__ == "__main__":
    app = wx.App()
    frame = wx.Frame(parent=None, title='Hello World')
    frame.Show()
    app.MainLoop()
```

There are two to resolve the problem:
1. Report the problem to matplotlib: https://github.com/matplotlib/matplotlib .
2. Uninstall matplotlib - pyclustering may work without it (only visualization services won't be available).

**Comment by liufsd** [comment]
amazing ....
