### ISSUE TITLE
Use random restarts to give consistent results

### ISSUE THREAD

**Issue by LemonPi** [annoviko/pyclustering#525]
Currently only 1 run of kmeans is done inside the improve parameters method, and this often leads to local minima even on the simplest examples (below is the demo program ran twice). There should be an option for random reinitializations of kmeans, selecting the one yielding the lowest total distance inside this function to give consistent output at the tradeoff of increased runtime.

![ccore_on](https://user-images.githubusercontent.com/5508542/60545431-0e230580-9ce9-11e9-8d3f-76a3b16f2802.png)
![ccore_off](https://user-images.githubusercontent.com/5508542/60545435-0fecc900-9ce9-11e9-9bdb-b337c6e10362.png)

**Comment by annoviko** [comment]
Hello, @LemonPi, thank you for your proposal, it looks nice. Have you got paper (or reference to it) that described this procedure? Or could you please write down details (steps) and I will support it?

**Comment by LemonPi** [comment]
https://www.cs.cmu.edu/~epxing/Class/10715-14f/project-reports/DannDickWong.pdf discusses how many restarts to use (I think you can just provide that as an option, no need for anything fancy), but for actually how to restart, you can just run kmeans again (the previous query for random.* will have altered the pseudorandom state). You then track the `get_total_wce()` of each call as well as the resulting clusters, then select the results with the minimum summed metric.

**Comment by annoviko** [comment]
@LemonPi , thank you for the paper and description.

**Comment by annoviko** [comment]
@LemonPi , the changes will be available in the next release. Currently they are available on 'master' branch. Be aware if the library is downloaded from repository then C++ part of the library should be built: https://github.com/annoviko/pyclustering/wiki/Core-of-the-PyClustering
