### ISSUE TITLE
[pyclustering.cluster.kmedians] predict method

### ISSUE THREAD

**Issue by annoviko** [annoviko/pyclustering#528]
**Introduction**
Introduce predict method to calculate closest clusters for specified points - classification method.

**Details**
K-Means can be considered as an example.

**Comment by ashvinmacaw** [comment]
Hi @annoviko, I am not much familiar with GitHub labels but I see a development label tag to this issue. Does this mean you are working on the predict function of Kmedians?

I tried to call predict function but it failed saying "'kmedoids' object has no attribute 'predict'.

**Comment by annoviko** [comment]
Hello, @ashvinmacaw , currently this functionality is available on branch 0.9.dev. And of course it will be available after release.
