### ISSUE TITLE
SKlearn Wrapper

### ISSUE THREAD

**Issue by SomeUserName1** [annoviko/pyclustering#533]
Hi,

in order to use GridSearch, Pipeline, etc. from SKLearn I tried to write a wrapper to be consistent with the SKLearn API.
Here is an example for KMeans that uses Jaccrd distance instead of Euclidean:
```
class KMeansWrapper(BaseEstimator, ClusterMixin):

    def __init__(self, n_clusters, tolerance=0.001, max_iter=200):
        self.n_clusters = n_clusters
        self.tolerance = tolerance
        self.metric = self.__jaccard
        self.max_iter = max_iter
        self.wrapped_instance = None
        self.labels_ = None
        self.centers_ = None

    def fit_predict(self, x, y=None):
        x = check_array(x, accept_sparse='csr')
        self.wrapped_instance = kmeans(data=x,
                                       initial_centers=kmeans_plusplus_initializer(x, self.n_clusters),
                                       tolerance=self.tolerance,
                                       metric=self.metric,
                                       itermax=self.max_iter)
        self.wrapped_instance.process()
        self.labels_ = self.wrapped_instance.get_clusters()
        self.centers_ = self.wrapped_instance.get_centers()

        return self.labels_

    def fit(self, x):
        x = check_array(x, accept_sparse='csr')
        self.wrapped_instance = kmeans(data=x,
                                       initial_centers=kmeans_plusplus_initializer(x, self.n_clusters),
                                       tolerance=self.tolerance,
                                       metric=self.metric,
                                       itermax=self.max_iter)
        self.wrapped_instance.process()

        self.labels_ = self.wrapped_instance.get_clusters()
        self.centers_ = self.wrapped_instance.get_centers()

        return self

    @staticmethod
    def __jaccard(p1, p2):
        return (np.logical_and(p1, p2).sum() / float(np.logical_or(p1, p2).sum())).T
```

Am I abusing something here?

**Comment by annoviko** [comment]
Hello, @SomeUserName1 ,

There are several problems in your code.
1. Incorrect center initialization - you created instance for initialization, but didn't call it. Initialization should be following:
```
initial_centers=kmeans_plusplus_initializer(x, n_clusters).initialize()
```

2. Incorrect distance metric usage. You need to create distance metric instance:
```
metric = metric.distance_metric(metric.type_metric.USER_DEFINED, func=__jaccard)
```

3. I haven't checked correctness of Jaccard math description, but in your expression it always be equal to 1.0 for non-zero coordinates and as a result only one cluster will be allocated.

**Comment by SomeUserName1** [comment]
Thanks for the first 2 remarks!

Regarding the 3rd one: I'm trying to cluster categorical values, so basically booleans. The math is specified as:
`\frac{A \cap B}{A \cup B} `
which should yield a value between 0 (no intersection or little intersection with a lot of disjoined attributes) and 1 (equal attributes).
What is fed in is a binary count vectorized maxtrix of shape (n_samples, n_distinct_attributes_in_dataset).
The goal is to check if conceptual clustering like cobweb or trestle is the only feasible way to get a proper hierarchy from labeled instances. (Compared to e.g. KMeans/DBSCAN + Agglomerative clustering or HDBSCAN)
