### ISSUE TITLE
X-Means producing different clustering with each run

### ISSUE THREAD

**Issue by rtrad89** [annoviko/pyclustering#534]
I am sorry if the issue is redundant; I have rifled the issues for a similar concern but alas, to no avail.

Is there a way to pause the randomness in `X-Means`, so that the clusterings it produces are consistent (perhaps through fixing the `random_seed` or `random_state`)? Because I am doing some experiments and it's elusive if the `X-Means` results keep varying run after run.

Many thanks in advance!

**Comment by annoviko** [comment]
Hello, @rtrad89 ,

Currently, there is no such option. When X-Means tries to split clusters it should chose new centers for them and for that purpose K-Means++ is used.
