### ISSUE TITLE
cluster_visualizer_multidim() 

### ISSUE THREAD

**Issue by smazrouee** [annoviko/pyclustering#535]
Hi, when I tried: 
visualizer = cluster_visualizer_multidim()
visualizer.append_clusters(k_clusters, Dist_Mat)
visualizer.show()
--- Got value error:

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-42-a8e725db57c6> in <module>
----> 1 visualizer.show()

/usr/local/lib/python3.7/site-packages/pyclustering/cluster/__init__.py in show(self, pair_filter, **kwargs)
    194             raise ValueError("There is no non-empty clusters for visualization.")
    195 
--> 196         cluster_data = self.__clusters[0].data or self.__clusters[0].cluster
    197         dimension = len(cluster_data[0])
    198 

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all() 

A little background that: 

Dist_Mat = cdist(df, df, 'euclidean')
kmedoids_instance = kmedoids(Dist_Mat, initial_medoids, data_type='distance_matrix')
kmedoids_instance.process()
k = [DIFFERS FROM TIME TO TIME, RANGES 10-45] 
initial_medoids = [random.randint(1,20000) for i in range(k)]
k_clusters = kmedoids_instance.get_clusters()
k_medoids = kmedoids_instance.get_medoids()

I'm pretty sure it's dumb error.... can you help me with the visualization? thanks

**Comment by annoviko** [comment]
Hello, @smazrouee,

`cluster_visualizer_multidim` is not able to visualize data that is represented by distance matrix. The visualizer is able to display data that is represented by list of points, like [ [1.0, 2.0], [1.3, 2.1], [1.5, 1.9], ... ].

**Comment by smazrouee** [comment]
Thank you Andrei for the response! I figured that after spending some time. I'm using networkx for the visualization now (in case someone came across here).
