### ISSUE TITLE
Wish Kmedoids keep same centers order with my input index 

### ISSUE THREAD

**Issue by liufsd** [annoviko/pyclustering#536]
our default data_centers:
```
   [[0 0 0 0]
   [1 1 1 1]
      [1 2 1 2]
   [1 1 2 2]
       [1 2 2 3]]
```
input random `initial_medoids`
```
 initial_medoids = [1, 0,50,20,21]
```

but output centers:
```
     [[1 2 2 2]
       [0 0 0 0]
      [1 1 1 1]
       [1 2 2 3]
          [1 2 0 2]]
```

**Comment by annoviko** [comment]
Hello, K-Medoids do not return centers, only medoids (points that corresponds to input data). It does not re-order anything, it changes medoids in line with algorithm rules.

**Comment by liufsd** [comment]
yes, i means , i hope the medoids index like our data_centers (index)

**Comment by annoviko** [comment]
Medoids can be absolutely different from initial value at all. Even in your case you have [1 2 0 2] and [1 2 2 2] that do not correspond to initial. In other words [0 0 0 0] became [1 2 2 2], [1 1 1 1] -> [0 0 0 0], and so on.

**Comment by liufsd** [comment]
i do not care the medoids value . because of `points that corresponds to input data`. but i wish it base on my input order  like k-means.

**Comment by liufsd** [comment]
Maybe not support it ~

**Comment by annoviko** [comment]
It is based on your input like in K-Means, you can check code inside or visualize clustering process.
