### ISSUE TITLE
AttributeError: 'kmedoids' object has no attribute 'predict'

### ISSUE THREAD

**Issue by csitaula** [annoviko/pyclustering#537]
This code is raising an error:
'kmedoids' object has no attribute 'predict'
from pyclustering.cluster.kmedoids import kmedoids
from pyclustering.samples.definitions import SIMPLE_SAMPLES
from pyclustering.utils import read_sample
# Load list of points for cluster analysis.
sample = read_sample(SIMPLE_SAMPLES.SAMPLE_SIMPLE3)
# Initial medoids for sample 'Simple3'.
initial_medoids = [4, 12, 25, 37]
# Create instance of K-Medoids algorithm with prepared centers.
kmedoids_instance = kmedoids(sample, initial_medoids)
# Run cluster analysis.
kmedoids_instance.process()
# Calculate the closest cluster to following two points.
points = [[0.35, 0.5], [2.5, 2.0]]
closest_clusters = kmedoids_instance.predict(points)
print(closest_clusters)

**Comment by annoviko** [comment]
Hello, @csitaula ,
'predict' is not avaiable in release 0.9.0, it will be available in 0.9.1. If you need that functionality right now, then you can try to take it from github:
```bash
mkdir pyclustering
cd pyclustering
git clone https://github.com/annoviko/pyclustering.git .
```

And then in case of Linux or MacOS:
```bash
cd ccore
make ccore_x64
```

In case of Windows:
1. Open `ccore` directory.
2. Open `ccore.sln`
3. Build `ccore` project.
