### ISSUE TITLE
Pyclustering Optics 

### ISSUE THREAD

**Issue by Morenagl** [annoviko/pyclustering#538]
hello every one , i'm working on classification with optics in python the problem iid there is a lot of None index class i dont know where is the problem , and when i try to make it work on conda prompt doesn't work because there is none value in clusters 
@annoviko 
thank you for help
![Capture](https://user-images.githubusercontent.com/53742915/63346708-e00b8a80-c355-11e9-9bde-6453341a802a.PNG)

**Comment by annoviko** [comment]
Hello, @Morenagl ,

Could you please provide a little bit more details? For example, could you please provide code that you are using for clustering. By default, OPTICS return clusters (list of indexes) instead of cluster labels.

**Comment by Morenagl** [comment]
@annoviko thanks for responding I'm using pyclustering package; I am trying to cluster some data with least and long variables, I have a huge base I don't know exactly the minpnts that suitable for this case, I have used nearest neighbor distance and I fixed my minpnts to 100  it gives me 20, in some lectures I ve seen that you can precise 1 km or 20 but how you can mention the unit

**Comment by annoviko** [comment]
@Morenagl , looks like a lot of points are marked as a outliers. You can check method 'get_noise()'. You can set big minpts, check ordering diagram and estimate amount of clusters. And after that repeat clustering using parameter `amount_clusters`, see documentation: https://codedocs.xyz/annoviko/pyclustering/classpyclustering_1_1cluster_1_1optics_1_1optics.html

**Comment by Morenagl** [comment]
@annoviko  okey i understand but the problem for me is how i can visualise my noise i have it onely as a list because i have already  used visualizer but not work for me

**Comment by Morenagl** [comment]
@annoviko  thank you for all your explanation , its done
