### ISSUE TITLE
Optics Pyclustering

### ISSUE THREAD

**Issue by Morenagl** [annoviko/pyclustering#539]
![image](https://user-images.githubusercontent.com/53742915/63574910-20068380-c589-11e9-8937-7c06e13ebbbe.png)

i want to shoose the best parameter that cauld give me the right clustering after trying a lot of choice , is not work the akgorithm not have the right way to cluster my data points have you any seggestion in the picture i want to my algorithm to cluster at any drop of density how to make that possible  
@annoviko

**Comment by annoviko** [comment]
@Morenagl ,

Sorry, I cannot help you with data analysis, I am ready to help with the library.
