### ISSUE TITLE
XMeans predict() function

### ISSUE THREAD

**Issue by aditya-malte** [annoviko/pyclustering#540]
Hello,
I would like to ask that why is there no predict() function for the xmeans module?
After all it can be implemented by finding nearest cluster(I am eager to work on this idea)

Having a predict function would be useful in cases where you need to perform prediction with a trained model(without training it all over again)
Thanks

**Comment by annoviko** [comment]
Hello, @aditya-malte ,

Good point, I will add this function.

**Comment by aditya-malte** [comment]
That's amazing! Never expect such quick response and turnaround time.
Thanks
