### ISSUE TITLE
Extend data type for sequential algorithm (*sas)

### ISSUE THREAD

**Issue by jungla88** [annoviko/pyclustering#559]
Is there a way to use these algorithms with non-vectorial data structures such as strings or graphs? This should be straightforward if the updating rule could take a distance matrix as input or compute it in place by defining a suitable distance measure, as already defined in kmedoid.
Am I wrong or actually something similar is not yet implemented  for this algorithms?

**Comment by annoviko** [comment]
Hello @jungla88 ,

All algorithms are able to array-like data where each object is represented by numerical values. Some of them are able to work with data that is represented by connectivity matrix. 

Probably it is possible to use data that is represented by other data types + user defined distance metric, but I have never tested it against of it. I would recommend to encode your data to array_like data type with numerical values.
