### ISSUE TITLE
How do I build ccore on Jetson Xavier?

### ISSUE THREAD

**Issue by deltaautonomy** [annoviko/pyclustering#560]
How do I build ccore on Jetson Xavier (aarch64)?

**Comment by annoviko** [comment]
The instruction is the same for every platform: https://github.com/annoviko/pyclustering/wiki/Core-of-the-PyClustering .

**Comment by heethesh** [comment]
I had to remove the `CFLAG_PLATFORM` and `LFLAG_PLATFORM` flags in [`ccore.mk`](https://github.com/annoviko/pyclustering/blob/master/ccore/ccore.mk).

**Comment by annoviko** [comment]
@heethesh , that is true, if python version is differ from C++ then error is expected.

I think it is good idea to provide makefile target to build the `ccore` using default configuration of the target machine where building process is started.
