### ISSUE TITLE
[pyclustering.cluster.center_initializer] possible bug in random_center_initializer __create_center() method

### ISSUE THREAD

**Issue by dsmccormick8492** [annoviko/pyclustering#573]
First, thank you for a fabulous clustering library. 

I was having issues with the random_center_initializer: all the initial clusters seemed to be close to the first few data items.  

I think I found a bug in the `random_center_initializer` `__create_center()` method.

In **center_initializer.py**, see line 92:
```
   85     def __create_center(self, return_index):
   ...
   92         random_index_point = random.randint(0, len(self.__data[0]))
   93         if random_index_point not in self.__available_indexes:
   94             random_index_point = self.__available_indexes.pop()
   95         else:
   96             self.__available_indexes.remove(random_index_point)
   97 
   98         if return_index:
   99             return random_index_point
  100         return self.__data[random_index_point]
  101
```

in **line 92**, `self.__data[0]` refers to the first list element, which will only be as long as there are columns in the input data. 

I think you want line 92 to be: 
```
   92         random_index_point = random.randint(0, len(self.__data))
```

Now, `len()` returns the number of items in `__data`.

I have changed that locally and now `random_center_initializer.initialize()` returns a more uniformly distributed list of starting cluster centers. 

Cheers, David

**Comment by annoviko** [comment]
Hi @dsmccormick8492 ,

Good catch, thank you for your finding, looks like there is a mistake, I will double check it and correct the implementation.
