### ISSUE TITLE
Does Birch dynamically increment the diameter?

### ISSUE THREAD

**Issue by nabilEM** [annoviko/pyclustering#574]
In the original paper, a heuristic is proposed to adjust the value of the diameter as points are added in the cf-tree. I would like to know if your implementation integrates this heuristic or if the diameter remains the same during the construction of the cf-tree?

Thank you in advance for your answer

**Comment by annoviko** [comment]
Hi @nabilEM ,

Yes, if the amount of points for adding becomes bigger than the amount of points that can be stored in the tree, then the diameter is increased by `diameter_multiplier` value (by default 1.5).

**Comment by nabilEM** [comment]
thank you @annoviko for answering my question. I could suggest you the heuristic proposed by the authors of the original paper (http://www.cs.uoi.gr/~pitoura/courses/dm07/birch.pdf). This heuristic described in section 5.1.2 (Threshold Values) estimates the new diameter  based on leaf or root volumes as well as the statistical model called least squares linear regression. 

Also when the diameter is initialized to 0 and the number of nodes is exceeded the new diameter value is set to 1 by default (see the increased_diameter variable in the __rebuild_tree(self, index_point) function). However, if the values of the points are lower than 1 then the distances between points are probably lower than 1. As a consequence, the algorithm produces few clusters or even only one cluster.
