### ISSUE TITLE
setting random seed/state

### ISSUE THREAD

**Issue by dreizehnutters** [annoviko/pyclustering#575]
For scientific purposes it would be nice to set the numpy seed for every function/class, in order to get consistent results.

**Comment by annoviko** [comment]
Hi @dreizehnutters ,

do you mean to provide an opportunity to use the same seed for algorithms where random functions are used?

**Comment by dreizehnutters** [comment]
yes, this would be nice

**Comment by annoviko** [comment]
The issue #578 is allocated in order to cover this proposal.
