### ISSUE TITLE
Segmentation fault when using DBSCAN

### ISSUE THREAD

**Issue by Bill2462** [annoviko/pyclustering#576]
Hello!

I'm having issues with DBSCAN algorithm.

I have the following code which randomly produces segmentation fault.
```
std::vector<Cluster> DBSCAN::cluster(const FeatureDataset& dataset) const
{
    std::vector<FeatureVector> features = copyFeatures(dataset);
    pyclustering::clst::cluster_data clusters;
    
    //perform clustering
    pyclustering::clst::dbscan dbscan(0.1, 3;
    dbscan.process(features, clusters);
    
    //export clustering results
    return exportClusters(clusters, dataset);
}
```
Vagrind shows 2 errors: invalid read of size 8 and
 Invalid free() / delete / delete[] / realloc() (the cause of segmentation fault).
All valgrind errors disappear when pyclustering::clst::dbscan is swapped for pyclustering::clst::rock so it seems to be an error in DBSCAN implementation and not in my program.

Valgrind log: 
[valgrind.log](https://github.com/annoviko/pyclustering/files/4133817/valgrind.log)

Full source code is available here: 
https://github.com/Bill2462/Cluster-Storm/tree/04884ca08677bef2f4bc95edb7da78795f2f8489/magic

Cheers!

**Comment by annoviko** [comment]
Hi @Bill2462 ,

Yes, there is mistake in the code:
```
pyclustering::clst::cluster_data clusters;
... ...
```

You are using so-called base class instead of `dbscan_data` that contains additional data `m_noise`. DBSCAN algorithm tries to write down information about outliers, but there is no memory for that. You should correct it in following way to make it workable:
```
pyclustering::clst::dbscan_data clusters;
```

Thank you for your feedback. It is good point to forbid usage of `cluster_data` where common part is located and update interface in order to request concrete type instead of so-called interface.

**Comment by Bill2462** [comment]
Thanks!

Changing `pyclustering::clst::cluster_data clusters;` to `pyclustering::clst::dbscan_data clusters;`
solved the problem.

I think that the issue is also a lack of C++ examples.
Without them I had to figure out the type by looking at the method prototype which suggests that the correct type is `pyclustering::clst::cluster_data`. 

```
    /**
    *
    * @brief    Performs cluster analysis of an input data.
    *
    * @param[in]  p_data: input data (points) for cluster analysis.
    * @param[out] p_result: clustering result of an input data.
    *
    */
    virtual void process(const dataset & p_data, cluster_data & p_result);
```

Maybe I will find some time and contribute a couple of simple C++ examples.

**Comment by annoviko** [comment]
@Bill2462 ,

Agree, I think it is time to create documentation for C/C++ pyclustering as well as for Python version.
