### ISSUE TITLE
[pyclustering.cluster] Windows Error 0xe06d7363 at kmedians_instance.process()

### ISSUE THREAD

**Issue by Dimidro** [annoviko/pyclustering#590]
Hello!

I'm trying to use pyclustering.cluster to clusterize set of data from [this Kaggle playground](url=https://www.kaggle.com/c/competitive-data-science-predict-future-sales/data).
At the step kmedians_instance.process() I got an error:

OSError                                   Traceback (most recent call last)
<ipython-input-9-f71624a84af2> in <module>
      7 kmedians_instance = kmedians(sample, initial_medians)
      8 # Run cluster analysis and obtain results.
----> 9 kmedians_instance.process()
     10 clusters = kmedians_instance.get_clusters()
     11 medians = kmedians_instance.get_medians()

~\Anaconda3\lib\site-packages\pyclustering\cluster\kmedians.py in process(self)
    121         if self.__ccore is True:
    122             ccore_metric = metric_wrapper.create_instance(self.__metric)
--> 123             self.__clusters, self.__medians = wrapper.kmedians(self.__pointer_data, self.__medians, self.__tolerance, self.__itermax, ccore_metric.get_pointer())
    124 
    125         else:

~\Anaconda3\lib\site-packages\pyclustering\core\kmedians_wrapper.py in kmedians(sample, centers, tolerance, itermax, metric_pointer)
     38 
     39     ccore.kmedians_algorithm.restype = POINTER(pyclustering_package)
---> 40     package = ccore.kmedians_algorithm(pointer_data, pointer_centers, c_double(tolerance), c_size_t(itermax), metric_pointer)
     41 
     42     result = package_extractor(package).extract()

OSError: [WinError -529697949] Windows Error 0xe06d7363

Code that returns this exception:

from pyclustering.cluster.kmedians import kmedians
from pyclustering.cluster import cluster_visualizer
# Load list of points for cluster analysis.
sample = np.array(items_cnt_shops_gr_pr['item_cnt_day'])
# Create instance of K-Medians algorithm.
initial_medians = [[0.2], [0]]
kmedians_instance = kmedians(sample, initial_medians)
# Run cluster analysis and obtain results.
kmedians_instance.process()

I'm trying to do k-median clusterization for one column.
Source files is okay. Pandas deal with it without any problems.

Anyway, it will be much better to provide human-readable exception instead of "[WinError -529697949] Windows Error 0xe06d7363".
Thank you for your attention!

**Comment by annoviko** [comment]
Hello, @Dimidro ,

Thank you for your report, could you please provide an example of your input? Taking into account your initial medians, your input data should be like this: [[0.1], [-3.2], [1.5], [2.04]] - one dimensional data.

I agree about errors that are provided by the C++ part of the library, I think I should make them human-readable to make it easier to understand what is going on inside.

**Comment by Dimidro** [comment]
Thank you for the fast responce.
Sample file - in attachment.
[sample.xlsx](https://github.com/annoviko/pyclustering/files/4219104/sample.xlsx)

**Comment by Dimidro** [comment]
I tried to run this sample on Jupyter Notebook in Ubuntu 18.04, but kernel constantly dying at "kmedians_instance.process()".

**Comment by annoviko** [comment]
Hello, @Dimidro ,

I have check kmedians using your input data. I do not exactly how do you convert your data to `numpy.array`, but it works in my case. Could you please check following:

```python
from pyclustering.cluster.kmedians import kmedians
from pyclustering.cluster import cluster_visualizer
import numpy

file = open('input.txt', 'r')
sample = [[float(val) for val in line.split()] for line in file if len(line.strip()) > 0]
sample = numpy.array(sample)    # move it to numpy.array to keep consistency
file.close()

initial_medians = [[0.2], [0]]
kmedians_instance = kmedians(sample, initial_medians)

kmedians_instance.process()

clusters = kmedians_instance.get_clusters()

visualizer = cluster_visualizer()
visualizer.append_clusters(clusters, sample)
visualizer.show()
```

I do not use `pandas`, so I just copied the data from the excel file to a text file that is attached to the message.
[input.txt](https://github.com/annoviko/pyclustering/files/4239330/input.txt)

![Figure_1](https://user-images.githubusercontent.com/6785869/75091869-52159400-5572-11ea-8f91-36bc594e89ae.png)

Here is an input for the algorithm:
```
[[-8.46628326e-01]
 [-9.39639709e-01]
 [-5.20467720e-01]
 [-5.59524224e-01]
 [-2.90749951e-01]
 [-3.11097269e-01]
 [ 6.84317657e-01]
 [ 1.07850555e-01]
 [-9.86473027e-01]
 [-7.74878166e-01]
 [-6.25601276e-01]
 [-1.03860010e+00]
 [ 2.18553759e-01]
 [-7.07680287e-01]
 [-2.48796541e-01]
 [ 1.79290333e-01]
 [ 1.43046240e-02]
 [-6.02926087e-01]
 [ 8.07437900e-02]
 [ 2.18157159e-01]
 [-9.47209601e-01]
 [ 1.33750277e-01]
 [-9.88799200e-03]
 [-9.15602285e-01]
 [ 5.31542060e-02]
 [ 3.12308164e+00]
 [ 1.22197139e-01]
 [ 1.30798019e+00]
 [ 2.13394334e+00]
 [-3.60463660e-02]
 [ 4.23615000e-04]
 [ 4.31041661e+00]
 [-8.97048290e-01]
 [-9.53934562e-01]
 [-9.37225621e-01]
 [ 1.41613308e-01]
 [-1.04277302e+00]
 [-2.50848516e-01]
 [-1.19280690e-01]
 [-7.61928305e-01]
 [-9.63228803e-01]
 [-1.97945490e-01]
 [ 1.45070455e+00]
 [-1.75804849e-01]
 [-2.73575435e-01]
 [-3.26047374e-01]
 [ 3.13599874e-01]
 [ 1.17834536e-01]
 [-6.18945289e-01]
 [-7.53772134e-01]
 [ 2.66145790e-01]
 [-2.07550113e-01]
 [-1.90703224e-01]
 [ 1.47184680e-02]
 [ 2.15520457e+00]
 [ 4.45669490e-02]
 [ 2.97891055e-01]
 [ 1.38471372e+00]
 [ 3.60916009e-01]
 [-2.03653085e-01]]
```

Are you sure that in your case each point is represented by separate array? Each point is represented by sequence of coordinates, so for 1D: `[x]`, for 2D `[x, y]`, 3D - `[x, y, z]`.

**Comment by Dimidro** [comment]
Hello, @annoviko !
Thank you for response!
I'm glad to know that your module working.

>  I do not exactly how do you convert your data to numpy.array

I converted from pandas.series to array by function "np.array", the same as you.

> Are you sure that in your case each point is represented by separate array? Each point is represented by sequence of coordinates

There is single-dimension set of objects in my case.
It seems that problem in the input data remake from pd.series to np.array?
Or what else?

**Comment by annoviko** [comment]
Hi @Dimidro ,

Be sure that your each point is represented by container, not by a single value, your input shouldn't be following: `[1.1, 1.4, 2.6, 4.5, 2.3, ...]`, but `[[1.1], [1.4], [2.6], [4.5], [2.3], ...].

**Comment by Dimidro** [comment]
Thank you for your help!
Now I understand why I get this error.

Please, make more human-readable descriptions for expection :)
