### ISSUE TITLE
how to load data files other than sample files

### ISSUE THREAD

**Issue by yashbetala** [annoviko/pyclustering#594]
Hi
I'm using CLQUE alogrithm from pyclustering library. i'm facing problem loading my own data file to the algorithm. the file is in text format, but it still shows error.
the code snippet is -  

`from pyclustering.cluster.clique import clique, clique_visualizer
from pyclustering.utils import read_sample
from pyclustering.samples.definitions import **FCPS_SAMPLES**

data = read_sample(**FCPS_SAMPLES.SAMPLE_TARGET**)`

please help me.
thank you!

**Comment by annoviko** [comment]
Hi, @yashbetala ,

Your data should be represented as a list of points (each point is also represented as a list even in case 1D), for example 2D: `data = [[1.0, 2.0], [3.2, 2.3], [4.1, -3.4], [2.3, 4.5]]`

`read_sample` just reads data from text file with following format:
```
<coordinate 1: double> <coordinate 2: double> ... <coordinate N: double>
<coordinate 1: double> <coordinate 2: double> ... <coordinate N: double>
```

In case sample that are presented before:
```
1.0 2.0
3.2 2.3
4.1 -3.4
2.3 4.5
```
