### ISSUE TITLE
A bug in K-Medoids implementation

### ISSUE THREAD

**Issue by SajjadRahmani** [annoviko/pyclustering#595]
I think there should be a bug in K-Medoids algorithm implementation.
I have solved a simple example by hand and also code it with another implementation [here](https://github.com/letiantian/kmedoids), but with your package, I get different result which I think is a sign of bug in your algorithm implementation.
Here is my code:
`import numpy as np
import matplotlib.pyplot as plt

x=np.array([
    [5,6],#A
    [6,6],#B
    [6,5],#C
    [6,2],#D
    [6,1],#E
    [5,1],#F
    [2,3],#G
])

from pyclustering.cluster.kmedoids import kmedoids
from pyclustering.cluster import cluster_visualizer
from pyclustering.utils.metric import distance_metric, type_metric

metric = distance_metric(type_metric.MINKOWSKI, degree=1)
model=kmedoids(x,initial_index_medoids=[4,5],metric=metric)
model.process()

clusters = model.get_clusters()
medoids = model.get_medoids()
print("clusters: ",clusters)
print("medoids: ",medoids)

# Display clusters.
visualizer = cluster_visualizer()
visualizer.append_clusters(clusters, x,markersize=20)
visualizer.show()

plt.show()`

The output is:
clusters:  [[1, 0, 2, 3, 4, 6], [5]]
medoids:  [1, 5]

which is not true!

**Comment by annoviko** [comment]
Thank you for the reporting. This is known issue: #503 .
