### ISSUE TITLE
GA: add a get_labels() or predict() method

### ISSUE THREAD

**Issue by Gabriel-p** [annoviko/pyclustering#598]
Currently the GA class hast the `get_clusters()` method which returns a list of `K` sub-lists (where `K` is the number of clusters) each containing the indexes of the elements that correspond to that cluster. Usually one wants the labels of each element that associate it with a given cluster, somethign like this:

    labels = np.zeros(data.shape[0])
    for i, clust in enumerate(ga_instance.get_clusters()):
        labels[clust] = i
    labels = labels.astype(int)

The clustering methods in `scikit-learn` all have a unified `labels_` method that returns this.

**Comment by annoviko** [comment]
@Gabriel-p ,

I am sorry, but the interface is unified for each algorithm in the library since 2014. To overcome that problem you can use `cluster_encoder`. Here is an example with K-Means:

```python
# load list of points for cluster analysis
sample = read_sample(path);
# create instance of K-Means algorithm
kmeans_instance = kmeans(sample, [ [0.0, 0.1], [2.5, 2.6] ]);
# run cluster analysis and obtain results
kmeans_instance.process();
clusters = kmeans_instance.get_clusters();
# by default k-means returns representation CLUSTER_INDEX_LIST_SEPARATION
type_repr = kmeans_instance.get_cluster_encoding();
encoder = cluster_encoder(type_repr, clusters, sample);
# change representation from index list to label list
representor.set_encoding(type_encoding.CLUSTER_INDEX_LABELING);
# change representation from label to object list
representor.set_encoding(type_encoding.CLUSTER_OBJECT_LIST_SEPARATION);
```
