### ISSUE TITLE
[C++ pyclustering] CMake script to build the library

### ISSUE THREAD

**Issue by annoviko** [annoviko/pyclustering#603]
**Introduction**
CMake script to build the library is required in order to provide C++ library for static compilation to different projects. It is OK for Linux/Macos now because they are served by the makefile that is more or less independent from an user environment, but for Windows there is only VS2015 that should be manually converted to VS2017 or VS2020.

**Description**
- [x] Implement CMake script should support all existed build targets in makefile and VS2015.
- [x] Support the build system to use the created CMake.
- [x] Update documentation including wiki-pages.

**Comment by barcode** [comment]
I created a cmake script to use ccore from C++ (exprted targets etc.).
https://gitlab.com/cmake-wrappers/pyclustering
This could be used as a basis or as a stopgap until a more complete cmake script is finished.

**Comment by annoviko** [comment]
Hi @barcode ,

Thank you for your contribution, I will use it as a basis for the complete cmake that will cover all requirements.
