### ISSUE TITLE
Tests don't work

### ISSUE THREAD

**Issue by SnarkBoojum** [annoviko/pyclustering#607]
I'm trying to package pyclustering in Debian, but I have a hard time running the tests : "python3 setup.py test" shows a window with a graph, and when I close it, I get an error AttributeError: 'hysteresis_dynamic' object has no attribute 'allocate_clusters'.

Notice that graphical tests don't fly with automated testing, which is what Debian packages typically get.

**Comment by annoviko** [comment]
Hi @SnarkBoojum ,

Yes, that is true, tests are not run through the `setup.py`. I didn't support the correct behavior of `python3 setup.py test`.  They are run in a different way, there is an example from the build system on Linux (Ubuntu): https://travis-ci.org/github/annoviko/pyclustering/jobs/698190662 . The graphical tests are run as well, but with switched off GUI.

I can support `python3 setup.py test` if it is needed.

**Comment by SnarkBoojum** [comment]
Debian packages describe their deps and a test command, and the test servers build, install and check packages with this information - no network, no gui.

So I would need an easy way (the usual is indeed python3 setup.py test or tox) to run the tests against the already-built-and-installed package.

It would be nice if you could provide this, thanks!

**Comment by annoviko** [comment]
@SnarkBoojum , good point, thank you for the use case. I will support the command `python3 setup.py test`.

**Comment by annoviko** [comment]
@SnarkBoojum , I have supported `python3 setup.py test`. It is available on `master` branch. And it is going to be available in the next release - `0.10.0`.
