### ISSUE TITLE
Find Purity score for Kmeans Clustering 

### ISSUE THREAD

**Issue by rathishme** [annoviko/pyclustering#620]
Hello,
Looking to find purity score for Kmeans Clustering using different distance metrics, helps to decide the best approach.

**Comment by annoviko** [comment]
Hi @rathishme ,

Right now there is no any purity score for K-Means, you have to calculate them by yourself. There is a WCE that could be used as an estimation, but it is not an external evaluation.

I am ready to say that it will be implemented soon, because I do not have enough time to work on this library last two months. But I will take this proposal into account when will plan the next release.

**Comment by Lassi-CaiZ** [comment]
> Hi @rathishme ,
> 
> Right now there is no any purity score for K-Means, you have to calculate them by yourself. There is a WCE that could be used as an estimation, but it is not an external evaluation.
> 
> I am ready to say that it will be implemented soon, because I do not have enough time to work on this library last two months. But I will take this proposal into account when will plan the next release.

I'm also confuse about the calculating of clustering purity because of the label of each cluster is consitantly changing each time I run the code. Just wondering if it is possible to define the name of each clusters?

**Comment by annoviko** [comment]
@Lassi-CaiZ ,

Could you please to point to the paper that you are using in order to calculate the clustering purity? As far as I know there are several various clustering purity estimation and some of them are not considering internal process of clustering.

Regarding to your question, there is no way to assign names to clusters.

Technically, if the amount of clusters is not changed, then you can use cluster indexes for identification. There is an example of cluster evolution on each step (it is not perfect, to fast without detailed visualization, but it demonstrates that it is possible to see how does each cluster change): https://www.youtube.com/watch?v=X2pNYxFJ25o . So if you need the evolution then you can use `kmeans_observer` to get information about clustering process on each step.

**Comment by rathishme** [comment]
> Hi @rathishme ,
> 
> Right now there is no any purity score for K-Means, you have to calculate them by yourself. There is a WCE that could be used as an estimation, but it is not an external evaluation.
> 
> I am ready to say that it will be implemented soon, because I do not have enough time to work on this library last two months. But I will take this proposal into account when will plan the next release.

Thats a great news , thanks for your help.

**Comment by Lassi-CaiZ** [comment]
Hi Andrei,
Thanks for you email, the purity score I'm using for my assignment is depends on the amount of correct clustered points in each cluster. For example the total amount of data points is 100. In the data set the class of each cluster is already been defined and there are 4 classes totally and each class has 25 data points. So if I run the kmeans clustering and fit on the data. After the process 20 data points was correctly been defined in class 1, 21 in class 2, 24 in class 3 and 20 in class 4. So the purity score is (20+21+24+20)*(1/100) which gives the purity of the clustering process. I'm new to python and machine learning so I'm not exactly sure about the exact name of the purity score but so far that's what I have been taught.
Anyway thanks for your email. Pyclustering package is a very useful package and help me alot with my assignment.


Kind regards,
Zhen Cai.



---Original---

**Comment by rathishme** [comment]
> Hi Andrei, Thanks for you email, the purity score I'm using for my assignment is depends on the amount of correct clustered points in each cluster. For example the total amount of data points is 100. In the data set the class of each cluster is already been defined and there are 4 classes totally and each class has 25 data points. So if I run the kmeans clustering and fit on the data. After the process 20 data points was correctly been defined in class 1, 21 in class 2, 24 in class 3 and 20 in class 4. So the purity score is (20+21+24+20)*(1/100) which gives the purity of the clustering process. I'm new to python and machine learning so I'm not exactly sure about the exact name of the purity score but so far that's what I have been taught. Anyway thanks for your email. Pyclustering package is a very useful package and help me alot with my assignment. Kind regards, Zhen Cai.
> […](#)
> ---Original--- From: "Andrei Novikov"<notifications@github.com&gt; Date: Mon, Aug 17, 2020 17:48 PM To: "annoviko/pyclustering"<pyclustering@noreply.github.com&gt;; Cc: "Lassi-CaiZ"<916276471@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;; Subject: Re: [annoviko/pyclustering] Find Purity score for Kmeans Clustering (#620) @Lassi-CaiZ , Could you please to point to the paper that you are using in order to calculate the clustering purity? As far as I know there are several various clustering purity estimation and some of them are not considering internal process of clustering. Regarding to your question, there is no way to assign names to clusters. Technically, if the amount of clusters is not changed, then you can use cluster indexes for identification. There is an example of cluster evolution on each step (it is not perfect, to fast without detailed visualization, but it demonstrates that it is possible to see how does each cluster change): https://www.youtube.com/watch?v=X2pNYxFJ25o . So if you need the evolution then you can use kmeans_observer to get information about clustering process on each step. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by rathishme** [comment]
> > Hi Andrei, Thanks for you email, the purity score I'm using for my assignment is depends on the amount of correct clustered points in each cluster. For example the total amount of data points is 100. In the data set the class of each cluster is already been defined and there are 4 classes totally and each class has 25 data points. So if I run the kmeans clustering and fit on the data. After the process 20 data points was correctly been defined in class 1, 21 in class 2, 24 in class 3 and 20 in class 4. So the purity score is (20+21+24+20)*(1/100) which gives the purity of the clustering process. I'm new to python and machine learning so I'm not exactly sure about the exact name of the purity score but so far that's what I have been taught. Anyway thanks for your email. Pyclustering package is a very useful package and help me alot with my assignment. Kind regards, Zhen Cai.
> > […](#)
> > ---Original--- From: "Andrei Novikov"<[notifications@github.com](mailto:notifications@github.com)> Date: Mon, Aug 17, 2020 17:48 PM To: "annoviko/pyclustering"<[pyclustering@noreply.github.com](mailto:pyclustering@noreply.github.com)>; Cc: "Lassi-CaiZ"<[916276471@qq.com](mailto:916276471@qq.com)>;"Mention"<[mention@noreply.github.com](mailto:mention@noreply.github.com)>; Subject: Re: [annoviko/pyclustering] Find Purity score for Kmeans Clustering (#620) @Lassi-CaiZ , Could you please to point to the paper that you are using in order to calculate the clustering purity? As far as I know there are several various clustering purity estimation and some of them are not considering internal process of clustering. Regarding to your question, there is no way to assign names to clusters. Technically, if the amount of clusters is not changed, then you can use cluster indexes for identification. There is an example of cluster evolution on each step (it is not perfect, to fast without detailed visualization, but it demonstrates that it is possible to see how does each cluster change): https://www.youtube.com/watch?v=X2pNYxFJ25o . So if you need the evolution then you can use kmeans_observer to get information about clustering process on each step. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by rathishme** [comment]
Hello @Lassi-CaiZ :
Yes , indeed i do use the same logic.
Have you calculated the same using pyclustering, if so do you mind sharing the syntax to do so .

**Comment by bishnoink** [comment]
Here is the link on cluster purity: https://nlp.stanford.edu/IR-book/html/htmledition/evaluation-of-clustering-1.html

Thanks

**Comment by annoviko** [comment]
Two issues are opened in order to cover this request (proposal): #631, #632.
