### ISSUE TITLE
Question regards clusters result representation

### ISSUE THREAD

**Issue by Lassi-CaiZ** [annoviko/pyclustering#621]
Hi, I'm new to python and using pyclustering for clustering. I met a problem when represent the clustering result. The result was shown in index way like [1,2,3....][120.121.122..]. However as I want to visulize te cluster more clearly so I want to change it to shown in label form like 1,0,2,1,1,1,1..... I have already look the set_encoding samples but it is a little bit hard for me to understand because some of the variables has not been defined. Can someone help me with this please? The code is below.

#Minkowski

metric = distance_metric(type_metric.MINKOWSKI, degree=1)

Minkowski_kmeans_instance = kmeans(Df_Q1, initial_centers)

Minkowski_kmeans_instance.process()
Minkowski_clusters = Minkowski_kmeans_instance.get_clusters()
Minkowski_final_centers = Minkowski_kmeans_instance.get_centers()

Minkowski_type_repr = Minkowski_kmeans_instance.get_cluster_encoding()
Minkowski_encoder = Minkowski_cluster_encoder(Minkowski_type_repr, Minkowski_clusters, Df_Q1)

Minkowski_type_repr.set_encoding(type_encoding.CLUSTER_INDEX_LABELING)
print("Index Labeling:", Minkowski_encoder.get_clusters())

**Comment by annoviko** [comment]
Hi @Lassi-CaiZ,

There are few mistakes in your code, here is an correct version where I was using `SAMPLE_SIMPLE1` for cluster analysis:
```python
from pyclustering.utils import read_sample
from pyclustering.samples.definitions import SIMPLE_SAMPLES

from pyclustering.cluster.encoder import type_encoding, cluster_encoder
from pyclustering.cluster.kmeans import kmeans
from pyclustering.utils.metric import type_metric, distance_metric

Df_Q1 = read_sample(SIMPLE_SAMPLES.SAMPLE_SIMPLE1)
initial_centers = [[3.0, 5.1], [6.5, 8.6]]

metric = distance_metric(type_metric.MINKOWSKI, degree=1)

Minkowski_kmeans_instance = kmeans(Df_Q1, initial_centers)

Minkowski_kmeans_instance.process()
Minkowski_clusters = Minkowski_kmeans_instance.get_clusters()
Minkowski_final_centers = Minkowski_kmeans_instance.get_centers()

Minkowski_type_repr = Minkowski_kmeans_instance.get_cluster_encoding()
Minkowski_encoder = cluster_encoder(Minkowski_type_repr, Minkowski_clusters, Df_Q1)

Minkowski_encoder.set_encoding(type_encoding.CLUSTER_INDEX_LABELING)
print("Index Labeling:", Minkowski_encoder.get_clusters())
```

Output:
```
Index Labeling: [0, 0, 0, 0, 0, 1, 1, 1, 1, 1]
```

I hope it will help you.

**Comment by Lassi-CaiZ** [comment]
> Hi @Lassi-CaiZ,
> 
> There are few mistakes in your code, here is a correct version where I was using `SAMPLE_SIMPLE1` for cluster analysis:
> 
> ```python
> from pyclustering.utils import read_sample
> from pyclustering.samples.definitions import SIMPLE_SAMPLES
> 
> from pyclustering.cluster.encoder import type_encoding, cluster_encoder
> from pyclustering.cluster.kmeans import kmeans
> from pyclustering.utils.metric import type_metric, distance_metric
> 
> Df_Q1 = read_sample(SIMPLE_SAMPLES.SAMPLE_SIMPLE1)
> initial_centers = [[3.0, 5.1], [6.5, 8.6]]
> 
> metric = distance_metric(type_metric.MINKOWSKI, degree=1)
> 
> Minkowski_kmeans_instance = kmeans(Df_Q1, initial_centers)
> 
> Minkowski_kmeans_instance.process()
> Minkowski_clusters = Minkowski_kmeans_instance.get_clusters()
> Minkowski_final_centers = Minkowski_kmeans_instance.get_centers()
> 
> Minkowski_type_repr = Minkowski_kmeans_instance.get_cluster_encoding()
> Minkowski_encoder = cluster_encoder(Minkowski_type_repr, Minkowski_clusters, Df_Q1)
> 
> Minkowski_encoder.set_encoding(type_encoding.CLUSTER_INDEX_LABELING)
> print("Index Labeling:", Minkowski_encoder.get_clusters())
> ```
> 
> Output:
> 
> ```
> Index Labeling: [0, 0, 0, 0, 0, 1, 1, 1, 1, 1]
> ```
> 
> I hope it will help you.

Thank you su much, that really helps me a lot!
