### ISSUE TITLE
CLIQUE CLUSTERING: [WinError -529697949] Windows Error 0xe06d7363

### ISSUE THREAD

**Issue by guner-cyber** [annoviko/pyclustering#634]
Hi, 
i have a problem with the clique clustering algorithm. When i try to cluster my dataset([Zvectors.txt](https://github.com/annoviko/pyclustering/files/5365182/Zvectors.txt), my dataset has the following shape: [[]] ), i have to set the treshold and the interval. The problem is that if the value for the interval is anything other than 1 i get following error: **[WinError -529697949] Windows Error 0xe06d7363**
With intervall=1 i get only one cluster which is not useful. 
What could be the problem which causes this behaviour/error?

My code section for the clique clustering:

`from pyclustering.cluster import cluster_visualizer
from pyclustering.cluster.optics import optics, ordering_analyser, ordering_visualizer
from pyclustering.cluster.clique import clique, clique_visualizer
from pyclustering.cluster.dbscan import dbscan
from pyclustering.utils import read_sample
from pyclustering.samples.definitions import FCPS_SAMPLES
from pyclustering.cluster import cluster_visualizer_multidim

clique_instance=clique(Zvectors,10,15)
clique_instance.process()

clusters = clique_instance.get_clusters()  
noise = clique_instance.get_noise() 
cells = clique_instance.get_cells()`

**Comment by guner-cyber** [comment]
I have another issue, i tried Clique clustering with a little dataset([mini.txt](https://github.com/annoviko/pyclustering/files/5367491/mini.txt)), which i created for testing. I thought it would be easy for the algorithm to cluster such a little datatset. When i set the interval=4 the programm crashed and after interval=5 the error **[WinError -529697949] Windows Error 0xe06d7363** occured.

**Comment by annoviko** [comment]
Hello @guner-cyber ,

Thank you for reporting. I am investigating the problem, but it looks like the problem in the memory. This algorithm is not suitable for data when `N` (dimension) is to big like in your case. In case of your example (mini.txt) when there are 12 dimensions:
`N = 12, interval = 1`: amount of blocks to analyze: `interval^N = 1^12 = 1`;
`N = 12, interval = 2`: amount of blocks to analyze: `interval^N = 2^12 = 4.096`;
`N = 12, interval = 3`: amount of blocks to analyze: `interval^N = 3^12 = 531.441`;
`N = 12, interval = 4`: amount of blocks to analyze: `interval^N = 4^12 = 16.777.216`;
`N = 12, interval = 5`: amount of blocks to analyze: `interval^N = 5^12 = 244.140.625`;

CLIQUE block is described by the following:
```
private:
    clique_block_location     m_logical_location;  /* ~N * 8 bytes. */
    clique_spatial_block      m_spatial_location;   /* (N + N) * 8 bytes */
    content                   m_points;                        /* depends on amount of data points, suppose nothing is captured - 4 byte. */
    bool                      m_visited = false; /* depends on bool implementation, suppose 1 bytes. */
```

Approximately the minimum size of the block: `(8 * N + 16 * N + 5) = `24 * N + 5` bytes.
Lets back to `N = 12, interval = 4`, where it is needed 16.777.216 blocks: `16.777.216 * 25 + 5` = 402 MB to store all CLIQUE blocks.

But I have to investigate the issue before making the final statement.

**Comment by annoviko** [comment]
I have finished investigation. As I suspected the problem in the memory. The algorithm is not suitable for high dimensional data because of memory consumption. I have introduced a human-readable error, now it going to provide the following statement if `bad_alloc` problem is detected:
```
Traceback (most recent call last):
  File "D:/workspace/pyclustering/pyclustering/cluster/examples/zexample.py", line 13, in <module>
    clique_instance.process()
  File "D:\workspace\pyclustering\pyclustering\cluster\clique.py", line 536, in process
    self.__process_by_ccore()
  File "D:\workspace\pyclustering\pyclustering\cluster\clique.py", line 606, in __process_by_ccore
    raise RuntimeError("Error has been detected. " + result)
RuntimeError: Error has been detected. There is not enough memory to perform cluster analysis using CLIQUE algorithm. CLIQUE algorithm might not be suitable in case of high dimension data because CLIQUE is a grid-based algorithm and the amount of CLIQUE blocks (cells) is defined as '[amount_intervals]^[amount_dimensions]'.
```

The problem could easily reproduced using the following data:
```
data = [[0, 1, 2, 1, 3, 4, 5, 1, 2, 3, 3, 1, 3], [0, 1, 0, 1, 3, 8, 5, 5, 3, 3, 3, 0, 0]]
```

**Comment by annoviko** [comment]
There a issue that is regarded to optimization where I am going to resolve memory consumption problem for high dimensional data.
