### ISSUE TITLE
Pick the best value of Epsilon in DBSCAN?

### ISSUE THREAD

**Issue by sagarsen78** [annoviko/pyclustering#678]
We always predetermine the value of Epsilon in DBSCAN. But is there any way to select the best value which gives us the utmost accuracy for selection?

**Comment by annoviko** [comment]
Hello @sagarsen78 ,

OPTICS algorithm is implemented to make it easier - to find proper epsilon parameter. I would recommend to look at this algorithm, it is well-known algorithm and there are plenty of implementations nowadays. There is link to the OPTICS pyclustering documentation: https://pyclustering.github.io/docs/0.10.1/html/de/d3b/classpyclustering_1_1cluster_1_1optics_1_1optics.html
